<!-- Welcome Content include begins -->
The caCORE Software Development Kit (SDK) is a set
of tools that can be used by an intermediate Java 
developer to create a 'caCORE-like' system. Such 
systems are constructed using certain design principles:
<br>
<br>
<ul>
	<li>
		UML Modeling
	</li>
	<li>
		N-tier architecture with open API's
	</li>
	<li>
		Controlled vocabularies
	</li>
	<li>
		Registered metadata
	</li>
</ul>

A system built along these lines is said to be
'semantically integrated', that is, there exists
runtime metadata that describes every class and
class attribute in the API.
<br>
<br>
The SDK consists of three components. The
<b>Semantic Connector</b> assists in the
annotation of the UML with appropriate controlled
vocabulary terms. The
<b>UML Loader</b> registers the annotated model in
the caDSR, a metadata repository, and the
<b>Code Generator</b> creates the software system
in Java.
<br>
<br>
<!-- Welcome Content include ends -->