
CREATE TABLE AD_AD_DATATYPE_VALUE9 (
	AD_DATATYPE_ID NUMBER(8) NOT NULL,
	AD_DATATYPE_VALUE9_ID NUMBER(8) NOT NULL
)
/

CREATE TABLE AD_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_AL_VALUE VARCHAR2(50),
	VALUE2_DAL_VALUE VARCHAR2(50),
	VALUE2_DAL_CODE VARCHAR2(50),
	VALUE3_AL_VALUE VARCHAR2(50),
	VALUE3_AL_CODE VARCHAR2(50),
	VALUE3_AL_CODESYSTEM VARCHAR2(50),
	VALUE4_AL1_VALUE VARCHAR2(50),
	VALUE4_AL2_VALUE VARCHAR2(50),
	VALUE4_AL1_CODE VARCHAR2(50),
	VALUE4_AL2_CODE VARCHAR2(50),
	VALUE4_AL1_CODESYSTEM VARCHAR2(50),
	VALUE4_AL2_CODESYSTEM VARCHAR2(50),
	VALUE5_AL_VALUE VARCHAR2(50),
	VALUE5_AL_CODE VARCHAR2(50),
	VALUE5_AL_CODESYSTEM VARCHAR2(50),
	VALUE5_DAL_CODE VARCHAR2(50),
	VALUE5_DAL_VALUE VARCHAR2(50),
	VALUE5_DAL_CODESYSTEM VARCHAR2(50),
	VALUE5_CTY_VALUE VARCHAR2(50),
	VALUE5_CTY_CODE VARCHAR2(50),
	VALUE5_CTY_CODESYSTEM VARCHAR2(50),
	VALUE6_ADL_VALUE VARCHAR2(50),
	VALUE6_AL_VALUE VARCHAR2(50),
	VALUE6_BNN_VALUE VARCHAR2(50),
	VALUE6_BNR_VALUE VARCHAR2(50),
	VALUE6_BNS_VALUE VARCHAR2(50),
	VALUE6_CAR_VALUE VARCHAR2(50),
	VALUE6_CEN_VALUE VARCHAR2(50),
	VALUE6_CNT_VALUE VARCHAR2(50),
	VALUE6_CPA_VALUE VARCHAR2(50),
	VALUE6_CTY_VALUE VARCHAR2(50),
	VALUE6_DAL_VALUE VARCHAR2(50),
	VALUE6_DEL_VALUE VARCHAR2(50),
	VALUE6_DINSTA_VALUE VARCHAR2(50),
	VALUE6_DINSTQ_VALUE VARCHAR2(50),
	VALUE6_DIR_VALUE VARCHAR2(50),
	VALUE6_DMOD_VALUE VARCHAR2(50),
	VALUE6_DMODID_VALUE VARCHAR2(50),
	VALUE6_INT_VALUE VARCHAR2(50),
	VALUE6_POB_VALUE VARCHAR2(50),
	VALUE6_PRE_VALUE VARCHAR2(50),
	VALUE6_SAL_VALUE VARCHAR2(50),
	VALUE6_STA_VALUE VARCHAR2(50),
	VALUE6_STB_VALUE VARCHAR2(50),
	VALUE6_STR_VALUE VARCHAR2(50),
	VALUE6_STTYP_VALUE VARCHAR2(50),
	VALUE6_UNID_VALUE VARCHAR2(50),
	VALUE6_UNIT_VALUE VARCHAR2(50),
	VALUE6_ZIP_VALUE VARCHAR2(50),
	VALUE6_ADL_CODE VARCHAR2(50),
	VALUE6_BNS_CODE VARCHAR2(50),
	VALUE6_BNS_CODESYSTEM VARCHAR2(50),
	VALUE6_DAL_CODE VARCHAR2(50),
	VALUE6_DAL_CODESYSTEM VARCHAR2(50),
	VALUE6_INT_CODE VARCHAR2(50),
	VALUE6_INT_CODESYSTEM VARCHAR2(50),
	VALUE6_STB_CODE VARCHAR2(50),
	VALUE6_STB_CODESYSTEM VARCHAR2(50),
	VALUE6_ZIP_CODESYSTEM VARCHAR2(50),
	VALUE6_ZIP_CODE VARCHAR2(50),
	AD_DATATYPE_VALUE8_ID NUMBER(8)
)
/

CREATE TABLE AD_DATATYPE_VALUE7 (
	AD_DATATYPE_ID NUMBER(8),
	AL_VALUE VARCHAR2(50),
	AL_CODE VARCHAR2(50),
	AL_CODESYSTEM VARCHAR2(50),
	DAL_CODE VARCHAR2(50),
	DAL_VALUE VARCHAR2(50),
	DAL_CODESYSTEM VARCHAR2(50),
	CTY_VALUE VARCHAR2(50),
	CTY_CODE VARCHAR2(50),
	CTY_CODESYSTEM VARCHAR2(50)
)
/

CREATE TABLE AD_DATATYPE_VALUE8 (
	ID NUMBER(8) NOT NULL,
	AL_VALUE VARCHAR2(50),
	AL_CODE VARCHAR2(50),
	AL_CODESYSTEM VARCHAR2(50),
	DAL_CODE VARCHAR2(50),
	DAL_VALUE VARCHAR2(50),
	DAL_CODESYSTEM VARCHAR2(50),
	CTY_VALUE VARCHAR2(50),
	CTY_CODE VARCHAR2(50),
	CTY_CODESYSTEM VARCHAR2(50)
)
/

CREATE TABLE AD_DATATYPE_VALUE9 (
	ID NUMBER(8) NOT NULL,
	AL_VALUE VARCHAR2(50),
	AL_CODE VARCHAR2(50),
	AL_CODESYSTEM VARCHAR2(50),
	DAL_CODE VARCHAR2(50),
	DAL_VALUE VARCHAR2(50),
	DAL_CODESYSTEM VARCHAR2(50),
	CTY_VALUE VARCHAR2(50),
	CTY_CODE VARCHAR2(50),
	CTY_CODESYSTEM VARCHAR2(50)
)
/

CREATE TABLE BL_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(1),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(1)
)
/

CREATE TABLE BL_NONNULL_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(1)
)
/

CREATE TABLE CD_CD_DATATYPE_VALUE8 (
	CD_DATA_TYPE_ID NUMBER(8) NOT NULL,
	CD_DATATYPE_VALUE8_ID NUMBER(8) NOT NULL
)
/

CREATE TABLE CD_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_CODE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_CODE VARCHAR2(50),
	VALUE3_CODE VARCHAR2(50),
	VALUE4_NULL_FLAVOR VARCHAR2(50),
	VALUE4_CODE VARCHAR2(50),
	VALUE4_CODE_SYSTEM VARCHAR2(50),
	VALUE4_CODE_SYSTEM_VERSION VARCHAR2(50),
	VALUE4_CODE_SYSTEM_NAME VARCHAR2(50),
	VALUE4_DISPLAY_NULL_FLAVOR VARCHAR2(50),
	VALUE4_DISPLAY_VALUE VARCHAR2(50),
	VALUE4_ORIG_TXT_NULL_FLAVOR VARCHAR2(50),
	VALUE4_ORIG_TXT_DESCRIPTION VARCHAR2(50),
	VALUE4_ORIG_TXT_VALUE VARCHAR2(50),
	VALUE5_NULL_FLAVOR VARCHAR2(50),
	VALUE5_CODE VARCHAR2(50),
	VALUE5_CODE_SYSTEM VARCHAR2(50),
	VALUE5_CODE_SYSTEM_NAME VARCHAR2(50),
	VALUE5_CODE_SYSTEM_VERSION VARCHAR2(50),
	VALUE5_DISPLAY_NULL_FLAVOR VARCHAR2(50),
	VALUE5_DISPLAY_VALUE VARCHAR2(50),
	VALUE5_ORIG_TXT_NULL_FLAVOR VARCHAR2(50),
	VALUE5_ORIG_TXT_DESCRIPTION VARCHAR2(50),
	VALUE5_ORIG_TXT_VALUE VARCHAR2(50),
	CD_DATATYPE_VALUE7_ID NUMBER(8)
)
/

CREATE TABLE CD_DATATYPE_VALUE6 (
	CD_DATATYPE_ID NUMBER(8) NOT NULL,
	NULL_FLAVOR VARCHAR2(50),
	CODE VARCHAR2(50),
	CODE_SYSTEM VARCHAR2(50),
	CODE_SYSTEM_NAME VARCHAR2(50),
	CODE_SYSTEM_VERSION VARCHAR2(50),
	DISPLAY_NULL_FLAVOR VARCHAR2(50),
	DISPLAY_VALUE VARCHAR2(50),
	ORIG_TXT_NULL_FLAVOR VARCHAR2(50),
	ORIG_TXT_DESCRIPTION VARCHAR2(50),
	ORIG_TXT_VALUE VARCHAR2(50)
)
/

CREATE TABLE CD_DATATYPE_VALUE7 (
	ID NUMBER(8) NOT NULL,
	NULL_FLAVOR VARCHAR2(50),
	CODE VARCHAR2(50),
	CODE_SYSTEM VARCHAR2(50),
	CODE_SYSTEM_NAME VARCHAR2(50),
	CODE_SYSTEM_VERSION VARCHAR2(50),
	DISPLAY_NULL_FLAVOR VARCHAR2(50),
	DISPLAY_VALUE VARCHAR2(50),
	ORIG_TXT_NULL_FLAVOR VARCHAR2(50),
	ORIG_TXT_DESCRIPTION VARCHAR2(50),
	ORIG_TXT_VALUE VARCHAR2(50)
)
/

CREATE TABLE CD_DATATYPE_VALUE8 (
	ID NUMBER(8) NOT NULL,
	NULL_FLAVOR VARCHAR2(50),
	CODE VARCHAR2(50),
	CODE_SYSTEM VARCHAR2(50),
	CODE_SYSTEM_NAME VARCHAR2(50),
	CODE_SYSTEM_VERSION VARCHAR2(50),
	DISPLAY_NULL_FLAVOR VARCHAR2(50),
	DISPLAY_VALUE VARCHAR2(50),
	ORIG_TXT_NULL_FLAVOR VARCHAR2(50),
	ORIG_TXT_DESCRIPTION VARCHAR2(50),
	ORIG_TXT_VALUE VARCHAR2(50)
)
/

CREATE TABLE DSET_AD_DATATYPE (
	ID NUMBER(8) NOT NULL
)
/

CREATE TABLE DSET_AD_DSET_AD_VALUE8 (
	DSET_AD_DATATYPE_ID NUMBER(8) NOT NULL,
	DSET_AD_VALUE8_ID NUMBER(8) NOT NULL
)
/

CREATE TABLE DSET_AD_VALUE1 (
	DSET_AD_DATATYPE_ID NUMBER(8) NOT NULL,
	ADXP_AL_VALUE VARCHAR2(50)
)
/

CREATE TABLE DSET_AD_VALUE2 (
	DSET_AD_DATATYPE_ID NUMBER(8) NOT NULL,
	ADXP_DAL_VALUE VARCHAR2(50),
	ADXP_DAL_CODE VARCHAR2(50)
)
/

CREATE TABLE DSET_AD_VALUE3 (
	DSET_AD_DATATYPE_ID NUMBER(8) NOT NULL,
	ADXP_AL_VALUE VARCHAR2(50),
	ADXP_AL_CODE VARCHAR2(50),
	ADXP_AL_CODESYSTEM VARCHAR2(50)
)
/

CREATE TABLE DSET_AD_VALUE4 (
	DSET_AD_DATATYPE_ID NUMBER(8) NOT NULL,
	ADXP_AL1_VALUE VARCHAR2(50),
	ADXP_AL2_VALUE VARCHAR2(50),
	ADXP_AL1_CODE VARCHAR2(50),
	ADXP_AL2_CODE VARCHAR2(50),
	ADXP_AL2_CODESYSTEM VARCHAR2(50),
	ADXP_AL1_CODESYSTEM VARCHAR2(50)
)
/

CREATE TABLE DSET_AD_VALUE5 (
	DSET_AD_DATATYPE_ID NUMBER(8) NOT NULL,
	ADXP_AL_VALUE VARCHAR2(50),
	ADXP_AL_CODE VARCHAR2(50),
	ADXP_AL_CODESYSTEM VARCHAR2(50),
	ADXP_DAL_CODE VARCHAR2(50),
	ADXP_DAL_CODESYSTEM VARCHAR2(50),
	ADXP_DAL_VALUE VARCHAR2(50),
	ADXP_CTY_VALUE VARCHAR2(50),
	ADXP_CTY_CODE VARCHAR2(50),
	ADXP_CTY_CODESYSTEM VARCHAR2(50)
)
/

CREATE TABLE DSET_AD_VALUE6 (
	DSET_AD_DATATYPE_ID NUMBER(8) NOT NULL,
	ADXP_ADL_VALUE VARCHAR2(50),
	ADXP_AL_VALUE VARCHAR2(50),
	ADXP_BNN_VALUE VARCHAR2(50),
	ADXP_BNR_VALUE VARCHAR2(50),
	ADXP_BNS_VALUE VARCHAR2(50),
	ADXP_CAR_VALUE VARCHAR2(50),
	ADXP_CEN_VALUE VARCHAR2(50),
	ADXP_CNT_VALUE VARCHAR2(50),
	ADXP_CPA_VALUE VARCHAR2(50),
	ADXP_CTY_VALUE VARCHAR2(50),
	ADXP_DAL_VALUE VARCHAR2(50),
	ADXP_DEL_VALUE VARCHAR2(50),
	ADXP_DINSTA_VALUE VARCHAR2(50),
	ADXP_DINSTQ_VALUE VARCHAR2(50),
	ADXP_DIR_VALUE VARCHAR2(50),
	ADXP_DMOD_VALUE VARCHAR2(50),
	ADXP_DMODID_VALUE VARCHAR2(50),
	ADXP_INT_VALUE VARCHAR2(50),
	ADXP_POB_VALUE VARCHAR2(50),
	ADXP_PRE_VALUE VARCHAR2(50),
	ADXP_SAL_VALUE VARCHAR2(50),
	ADXP_STA_VALUE VARCHAR2(50),
	ADXP_STB_VALUE VARCHAR2(50),
	ADXP_STR_VALUE VARCHAR2(50),
	ADXP_STTYP_VALUE VARCHAR2(50),
	ADXP_UNID_VALUE VARCHAR2(50),
	ADXP_UNIT_VALUE VARCHAR2(50),
	ADXP_ZIP_VALUE VARCHAR2(50),
	ADXP_ADL_CODE VARCHAR2(50),
	ADXP_BNS_CODE VARCHAR2(50),
	ADXP_BNS_CODESYSTEM VARCHAR2(50),
	ADXP_DAL_CODE VARCHAR2(50),
	ADXP_DAL_CODESYSTEM VARCHAR2(50),
	ADXP_INT_CODE VARCHAR2(50),
	ADXP_INT_CODESYSTEM VARCHAR2(50),
	ADXP_STB_CODE VARCHAR2(50),
	ADXP_STB_CODESYSTEM VARCHAR2(50),
	ADXP_ZIP_CODESYSTEM VARCHAR2(50),
	ADXP_ZIP_CODE VARCHAR2(50)
)
/

CREATE TABLE DSET_AD_VALUE7 (
	ID NUMBER(8) NOT NULL,
	DSET_AD_DATATYPE_ID NUMBER(8),
	ADXP_AL_VALUE VARCHAR2(50),
	ADXP_AL_CODE VARCHAR2(50),
	ADXP_AL_CODESYSTEM VARCHAR2(50),
	ADXP_DAL_CODE VARCHAR2(50),
	ADXP_DAL_CODESYSTEM VARCHAR2(50),
	ADXP_DAL_VALUE VARCHAR2(50),
	ADXP_CTY_VALUE VARCHAR2(50),
	ADXP_CTY_CODE VARCHAR2(50),
	ADXP_CTY_CODESYSTEM VARCHAR2(50)
)
/

CREATE TABLE DSET_AD_VALUE8 (
	ID NUMBER(8) NOT NULL,
	ADXP_AL_VALUE VARCHAR2(50),
	ADXP_AL_CODE VARCHAR2(50),
	ADXP_AL_CODESYSTEM VARCHAR2(50),
	ADXP_DAL_CODE VARCHAR2(50),
	ADXP_DAL_CODESYSTEM VARCHAR2(50),
	ADXP_DAL_VALUE VARCHAR2(50),
	ADXP_CTY_VALUE VARCHAR2(50),
	ADXP_CTY_CODE VARCHAR2(50),
	ADXP_CTY_CODESYSTEM VARCHAR2(50)
)
/

CREATE TABLE DSET_CD (
	ID NUMBER(8) NOT NULL
)
/

CREATE TABLE DSET_CD_CD_VALUE7 (
	DSET_CD_ID NUMBER(8) NOT NULL,
	DSET_CD_VALUE7_ID NUMBER(8) NOT NULL
)
/

CREATE TABLE DSET_CD_VALUE1 (
	DSET_CD_ID NUMBER(8) NOT NULL,
	CODE VARCHAR2(50)
)
/

CREATE TABLE DSET_CD_VALUE2 (
	DSET_CD_ID NUMBER(8) NOT NULL,
	CODE VARCHAR2(50),
	NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE DSET_CD_VALUE3 (
	DSET_CD_ID NUMBER(8) NOT NULL,
	CODE VARCHAR2(50),
	CODE_SYSTEM VARCHAR2(50),
	CODE_SYSTEM_NAME VARCHAR2(50)
)
/

CREATE TABLE DSET_CD_VALUE4 (
	DSET_CD_ID NUMBER(8) NOT NULL,
	CODE VARCHAR2(50),
	CODE_SYSTEM VARCHAR2(50),
	CODE_SYSTEM_NAME VARCHAR2(50),
	CODE_SYSTEM_VERSION VARCHAR2(50),
	DISPLAYABLE_VALUE VARCHAR2(50),
	ORIGINALTEXT_VALUE VARCHAR2(50),
	ORIGINALTEXT_DESC VARCHAR2(50)
)
/

CREATE TABLE DSET_CD_VALUE5 (
	DSET_CD_ID NUMBER(8) NOT NULL,
	CODE VARCHAR2(50),
	CODE_SYSTEM VARCHAR2(50),
	CODE_SYSTEM_NAME VARCHAR2(50),
	CODE_SYSTEM_VERSION VARCHAR2(50),
	DISPLAYABLE_VALUE VARCHAR2(50),
	ORIGINALTEXT_VALUE VARCHAR2(50),
	ORIGINALTEXT_DESC VARCHAR2(50)
)
/

CREATE TABLE DSET_CD_VALUE6 (
	ID NUMBER(8) NOT NULL,
	DSET_CD_ID NUMBER(8),
	CODE VARCHAR2(50)
)
/

CREATE TABLE DSET_CD_VALUE7 (
	ID NUMBER(8) NOT NULL,
	CODE VARCHAR2(50)
)
/

CREATE TABLE DSET_EN (
	ID NUMBER(8) NOT NULL
)
/

CREATE TABLE DSET_EN_VALUE1 (
	DSET_EN_DATATYPE_ID NUMBER(8) NOT NULL,
	ENXP_PN_VALUE VARCHAR2(50)
)
/

CREATE TABLE DSET_EN_VALUE2 (
	DSET_EN_DATATYPE_ID NUMBER(8) NOT NULL,
	ENXP_PN_VALUE VARCHAR2(50),
	ENXP_PN_CODE VARCHAR2(50)
)
/

CREATE TABLE DSET_EN_VALUE3 (
	DSET_EN_DATATYPE_ID NUMBER(8) NOT NULL,
	ENXP_PN_CODE VARCHAR2(50),
	ENXP_PN_VALUE VARCHAR2(50),
	ENXP_PN_CODESYSTEM VARCHAR2(50),
	ENXP_PN_CODESYSTEMVERSION VARCHAR2(50)
)
/

CREATE TABLE DSET_EN_VALUE4 (
	DSET_EN_DATATYPE_ID NUMBER(8) NOT NULL,
	ENXP_PN_VALUE VARCHAR2(50),
	ENXP_PN_ENPQ VARCHAR2(50)
)
/

CREATE TABLE DSET_EN_VALUE5 (
	DSET_EN_DATATYPE_ID NUMBER(8) NOT NULL,
	ENXP_PN_VALUE VARCHAR2(50),
	ENXP_PN2_VALUE VARCHAR2(50),
	ENXP_PN_CODE VARCHAR2(50),
	ENXP_PN2_CODE VARCHAR2(50),
	ENXP_PN_CODESYSTEM VARCHAR2(50),
	ENXP_PN2_CODESYSTEM VARCHAR2(50),
	ENXP_PN2_CODESYSTEMVERSION VARCHAR2(50),
	ENXP_PN_CODESYSTEMVERSION VARCHAR2(50)
)
/

CREATE TABLE DSET_EN_VALUE6 (
	DSET_EN_DATATYPE_ID NUMBER(8) NOT NULL,
	ENXP_PN_VALUE VARCHAR2(50),
	ENXP_PN_CODE VARCHAR2(50),
	ENXP_PN_CODESYSTEM VARCHAR2(50),
	ENXP_PN_CODESYSTEMVERSION VARCHAR2(50),
	ENXP_ON_VALUE VARCHAR2(50),
	ENXP_ON_CODE VARCHAR2(50),
	ENXP_ON_CODESYSTEM VARCHAR2(50),
	ENXP_ON_CODESYSTEMVERSION VARCHAR2(50)
)
/

CREATE TABLE DSET_EN_VALUE7 (
	DSET_EN_DATATYPE_ID NUMBER(8) NOT NULL,
	ENXP_PN_CODE VARCHAR2(50),
	ENXP_ON_CODE VARCHAR2(50),
	ENXP_PN_VALUE VARCHAR2(50),
	ENXP_ON_VALUE VARCHAR2(50),
	ENXP_ON_CODESYSTEM VARCHAR2(50),
	ENXP_PN_CODESYSTEM VARCHAR2(50),
	ENXP_ON_CODESYSTEMVERSION VARCHAR2(50),
	ENXP_PN_CODESYSTEMVERSION VARCHAR2(50)
)
/

CREATE TABLE DSET_II (
	ID NUMBER(8) NOT NULL
)
/

CREATE TABLE DSET_II_II_VALUE6 (
	DSET_II_ID NUMBER(8) NOT NULL,
	DSET_II_VALUE6_ID NUMBER(8) NOT NULL
)
/

CREATE TABLE DSET_II_VALUE1 (
	DSET_II_ID NUMBER(8) NOT NULL,
	EXTENSION VARCHAR2(50)
)
/

CREATE TABLE DSET_II_VALUE2 (
	DSET_II_ID NUMBER(8) NOT NULL,
	EXTENSION VARCHAR2(50),
	ROOT VARCHAR2(50),
	NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE DSET_II_VALUE3 (
	DSET_II_ID NUMBER(8) NOT NULL,
	EXTENSION VARCHAR2(50),
	IDENTIFIER_NAME VARCHAR2(50),
	DISPLAYABLE_VALUE VARCHAR2(50),
	RELIABILITY VARCHAR2(50),
	SCOPE VARCHAR2(50)
)
/

CREATE TABLE DSET_II_VALUE4 (
	DSET_II_ID NUMBER(8) NOT NULL,
	ROOT VARCHAR2(50),
	EXTENSION VARCHAR2(50),
	IDENTIFIER_NAME VARCHAR2(50),
	RELIABILITY VARCHAR2(50),
	SCOPE VARCHAR2(50),
	DISPLAYABLE_VALUE VARCHAR2(50),
	NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE DSET_II_VALUE5 (
	ID NUMBER(8) NOT NULL,
	DSET_II_ID NUMBER(8),
	EXTENSION VARCHAR2(50)
)
/

CREATE TABLE DSET_II_VALUE6 (
	ID NUMBER(8) NOT NULL,
	EXTENSION VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL (
	ID NUMBER(8) NOT NULL,
	NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_EMAIL (
	ID NUMBER(8) NOT NULL,
	NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_EMAIL_VALUE1 (
	DSET_TEL_EMAIL_ID NUMBER(8) NOT NULL,
	TEL_EMAIL_VALUE VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_EMAIL_VALUE2 (
	DSET_TEL_EMAIL_ID NUMBER(8),
	TEL_EMAIL_VALUE VARCHAR2(50),
	TEL_EMAIL_NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_PERSON (
	ID NUMBER(8) NOT NULL,
	NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_PERSON_VALUE1 (
	DSET_TEL_PERSON_ID NUMBER(8) NOT NULL,
	TEL_PERSON_VALUE VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_PHONE (
	ID NUMBER(8) NOT NULL,
	NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_PHONE_VALUE1 (
	DSET_TEL_PHONE_ID NUMBER(8) NOT NULL,
	TEL_PHONE_VALUE VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_TEL_VALUE_3 (
	DSET_TEL_ID NUMBER(8) NOT NULL,
	DSET_TEL_VALUE3_ID NUMBER(8) NOT NULL
)
/

CREATE TABLE DSET_TEL_URL (
	ID NUMBER(8) NOT NULL,
	NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_URL_VALUE1 (
	DSET_TEL_URL_ID NUMBER(8) NOT NULL,
	TEL_URL_VALUE VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_VALUE1 (
	DSET_TEL_ID NUMBER(8) NOT NULL,
	TEL_VALUE VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_VALUE2 (
	ID NUMBER(8) NOT NULL,
	DSET_TEL_ID NUMBER(8),
	TEL_VALUE VARCHAR2(50)
)
/

CREATE TABLE DSET_TEL_VALUE3 (
	ID NUMBER(8) NOT NULL,
	TEL_VALUE VARCHAR2(50)
)
/

CREATE TABLE ED_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_DATA BLOB,
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_DATA BLOB,
	VALUE2_COMPRESSION VARCHAR2(50),
	VALUE3_NULL_FLAVOR VARCHAR2(50),
	VALUE3_DATA BLOB,
	VALUE3_COMPRESSION VARCHAR2(50),
	VALUE3_DESCRIPTION VARCHAR2(50),
	VALUE3_VALUE VARCHAR2(50)
)
/

CREATE TABLE ED_TEXT_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(50),
	VALUE3_NULL_FLAVOR VARCHAR2(50),
	VALUE3_DESCRIPTION VARCHAR2(50),
	VALUE3_VALUE VARCHAR2(50)
)
/

CREATE TABLE EN_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_PN_VALUE VARCHAR2(50),
	VALUE2_PN_VALUE VARCHAR2(50),
	VALUE2_PN_CODE VARCHAR2(50),
	VALUE3_PN_VALUE VARCHAR2(50),
	VALUE3_PN_CODE VARCHAR2(50),
	VALUE3_PN_CODE_SYSTEM VARCHAR2(50),
	VALUE3_PN_CODE_SYSTEM_VERSION VARCHAR2(50),
	VALUE4_PN_VALUE VARCHAR2(50),
	VALUE4_PN_ENPQ VARCHAR2(50),
	VALUE5_PN_VALUE VARCHAR2(50),
	VALUE5_PN2_VALUE VARCHAR2(50),
	VALUE5_PN_CODE VARCHAR2(50),
	VALUE5_PN2_CODE VARCHAR2(50),
	VALUE5_PN_CODE_SYSTEM VARCHAR2(50),
	VALUE5_PN2_CODE_SYSTEM VARCHAR2(50),
	VALUE5_PN_CODE_SYSTEM_VERSION VARCHAR2(50),
	VALUE5_PN2_CODE_SYSTEM_VERSION VARCHAR2(50),
	VALUE6_PN_VALUE VARCHAR2(50),
	VALUE6_ON_VALUE VARCHAR2(50),
	VALUE6_PN_CODE VARCHAR2(50),
	VALUE6_ON_CODE VARCHAR2(50),
	VALUE6_PN_CODE_SYSTEM VARCHAR2(50),
	VALUE6_ON_CODE_SYSTEM VARCHAR2(50),
	VALUE6_PN_CODE_SYSTEM_VERSION VARCHAR2(50),
	VALUE6_ON_CODE_SYSTEM_VERSION VARCHAR2(50)
)
/

CREATE TABLE EN_ON_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_ON_VALUE VARCHAR2(50)
)
/

CREATE TABLE EN_PN_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_PN_VALUE VARCHAR2(50)
)
/

CREATE TABLE II_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_EXTENSION VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_ROOT VARCHAR2(50),
	VALUE2_EXTENSION VARCHAR2(50),
	VALUE3_NULL_FLAVOR VARCHAR2(50),
	VALUE3_EXTENSION VARCHAR2(50),
	VALUE3_IDENTIFIER_NAME VARCHAR2(50),
	VALUE3_RELIABILITY VARCHAR2(50),
	VALUE3_SCOPE VARCHAR2(50),
	VALUE3_DISPLAYABLE VARCHAR2(50),
	VALUE4_NULL_FLAVOR VARCHAR2(50),
	VALUE4_ROOT VARCHAR2(50),
	VALUE4_EXTENSION VARCHAR2(50),
	VALUE4_IDENTIFIER_NAME VARCHAR2(50),
	VALUE4_RELIABILITY VARCHAR2(50),
	VALUE4_SCOPE VARCHAR2(50),
	VALUE4_DISPLAYABLE VARCHAR2(1)
)
/

CREATE TABLE INT_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE NUMBER(8),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE NUMBER(8)
)
/

CREATE TABLE IVL_INT (
	ID NUMBER(8),
	VALUE1_LOW_VALUE NUMBER(8),
	VALUE1_HIGH_VALUE NUMBER(8),
	VALUE2_HIGH_VALUE NUMBER(8),
	VALUE2_LOWCLOSED VARCHAR2(50),
	VALUE3_ANY_VALUE NUMBER(8),
	VALUE3_HIGH_VALUE NUMBER(8),
	VALUE3_HIGH_CLOSED VARCHAR2(50),
	VALUE3_LOW_VALUE NUMBER(8),
	VALUE3_LOW_CLOSED VARCHAR2(50),
	VALUE3_WIDTH_VALUE NUMBER(8),
	VALUE3_NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE IVL_PQ (
	ID NUMBER(8) NOT NULL,
	VALUE1_LOW_VALUE NUMBER(8),
	VALUE2_LOW_VALUE NUMBER(8),
	VALUE2_LOW_PRECISION NUMBER(8),
	VALUE2_LOW_UNIT VARCHAR2(50),
	VALUE3_LOW_VALUE NUMBER(8),
	VALUE3_LOW_PRECISION NUMBER(8),
	VALUE3_LOW_UNIT VARCHAR2(50),
	VALUE3_NULL_FLAVOR VARCHAR2(50),
	VALUE4_HIGH_VALUE NUMBER(8),
	VALUE4_HIGH_PRECISION NUMBER(8),
	VALUE4_HIGH_UNIT VARCHAR2(50),
	VALUE4_HIGH_CLOSED VARCHAR2(50),
	VALUE4_HIGH_NULL_FLAVOR VARCHAR2(50),
	VALUE4_LOW_VALUE NUMBER(8),
	VALUE4_LOW_PRECISION NUMBER(8),
	VALUE4_LOW_UNIT VARCHAR2(50),
	VALUE4_LOW_NULL_FLAVOR VARCHAR2(50),
	VALUE4_LOW_CLOSED VARCHAR2(50),
	VALUE4_WIDTH_VALUE NUMBER(8),
	VALUE4_WIDTH_PRECISION NUMBER(8),
	VALUE4_WIDTH_UNIT VARCHAR2(50),
	VALUE4_WIDTH_NULL_FLAVOR VARCHAR2(50),
	VALUE4_NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE IVL_PQV (
	ID NUMBER(8) NOT NULL,
	VALUE1_LOW_VALUE NUMBER(8),
	VALUE1_HIGH_VALUE NUMBER(8),
	VALUE2_LOW_VALUE NUMBER(8),
	VALUE2_LOW_PRECISION NUMBER(8),
	VALUE2_HIGH_CLOSED VARCHAR2(50),
	VALUE3_LOW_VALUE NUMBER(8),
	VALUE3_LOW_PRECISION NUMBER(8),
	VALUE3_HIGH_VALUE NUMBER(8),
	VALUE3_HIGH_PRECISION NUMBER(8),
	VALUE3_HIGH_NULL_FLAVOR VARCHAR2(50),
	VALUE4_HIGH_VALUE NUMBER(8),
	VALUE4_HIGH_PRECISION NUMBER(8),
	VALUE4_HIGH_NULL_FLAVOR VARCHAR2(50),
	VALUE4_LOW_VALUE NUMBER(8),
	VALUE4_LOW_PRECISION NUMBER(8),
	VALUE4_LOW_NULL_FLAVOR VARCHAR2(50),
	VALUE4_WIDTH_VALUE NUMBER(8),
	VALUE4_WIDTH_PRECISION NUMBER(8),
	VALUE4_WIDTH_NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE IVL_REAL (
	ID NUMBER(8),
	VALUE1_LOW_VALUE NUMBER(8),
	VALUE1_HIGH_VALUE NUMBER(8),
	VALUE2_HIGH_VALUE NUMBER(8),
	VALUE2_LOW_CLOSED VARCHAR2(50),
	VALUE3_ANY_VALUE NUMBER(8),
	VALUE3_HIGH_VALUE NUMBER(8),
	VALUE3_HIGH_CLOSED VARCHAR2(50),
	VALUE3_LOW_VALUE NUMBER(8),
	VALUE3_LOW_CLOSED VARCHAR2(50),
	VALUE3_WIDTH_VALUE NUMBER(8),
	VALUE3_WIDTH_NULL_FLAVOR VARCHAR2(50),
	VALUE3_NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE IVL_TS (
	ID NUMBER(8),
	VALUE1_LOW_VALUE DATE,
	VALUE1_HIGH_VALUE DATE,
	VALUE2_HIGH_VALUE DATE,
	VALUE2_LOW_CLOSED VARCHAR2(50),
	VALUE3_HIGH_VALUE DATE,
	VALUE3_LOW_VALUE DATE,
	VALUE3_WIDTH_NULL_FLAVOR VARCHAR2(50),
	VALUE3_WIDTH_VALUE NUMBER(8),
	VALUE3_NULL_FLAVOR VARCHAR2(50)
)
/

CREATE TABLE PQ_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE NUMBER(8,2),
	VALUE1_UNIT VARCHAR2(50),
	VALUE2_VALUE NUMBER(8,2),
	VALUE3_NULL_FLAVOR VARCHAR2(50),
	VALUE3_UNIT VARCHAR2(50),
	VALUE3_VALUE NUMBER(8,2),
	VALUE3_PRECISION NUMBER(8),
	VALUE4_NULL_FLAVOR VARCHAR2(50),
	VALUE4_UNIT VARCHAR2(50),
	VALUE4_VALUE NUMBER(8,2),
	VALUE4_PRECISION NUMBER(8)
)
/

CREATE TABLE PQV_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE NUMBER(8,2),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE NUMBER(8,2),
	VALUE2_PRECISION NUMBER(8),
	VALUE3_VALUE NUMBER(8,2),
	VALUE3_PRECISION NUMBER(8),
	VALUE4_NULL_FLAVOR VARCHAR2(50),
	VALUE4_PRECISION NUMBER(8),
	VALUE4_VALUE NUMBER(8,2)
)
/

CREATE TABLE REAL_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE NUMBER(8,2),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE NUMBER(8,2)
)
/

CREATE TABLE SC_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(50),
	VALUE2_CODE_NULL_FLAVOR VARCHAR2(50),
	VALUE2_CODE_CODE VARCHAR2(50),
	VALUE2_CODE_CODE_SYSTEM VARCHAR2(50),
	VALUE2_CODE_CODE_SYSTEM_NAME VARCHAR2(50),
	VALUE2_CODE_CODE_SYSTEM_VER VARCHAR2(50),
	VALUE3_NULL_FLAVOR VARCHAR2(50),
	VALUE3_VALUE VARCHAR2(50),
	VALUE3_CODE_NULL_FLAVOR VARCHAR2(50),
	VALUE3_CODE_CODE VARCHAR2(50),
	VALUE3_CODE_CODE_SYSTEM VARCHAR2(50),
	VALUE3_CODE_CODE_SYSTEM_NAME VARCHAR2(50),
	VALUE3_CODE_CODE_SYSTEM_VER VARCHAR2(50),
	VALUE3_CODE_DISPLAY_NFLAVOR VARCHAR2(50),
	VALUE3_CODE_DISPLAY_VALUE VARCHAR2(50),
	VALUE3_CODE_ORIG_TXT_NFLAVOR VARCHAR2(50),
	VALUE3_CODE_ORIG_TXT_DESC VARCHAR2(50),
	VALUE3_CODE_ORIG_TXT_VALUE VARCHAR2(50)
)
/

CREATE TABLE ST_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(50)
)
/

CREATE TABLE ST_NT_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(50)
)
/

CREATE TABLE TEL_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(50)
)
/

CREATE TABLE TEL_EMAIL_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(50)
)
/

CREATE TABLE TEL_PERSON_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(50)
)
/

CREATE TABLE TEL_PHONE_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(50)
)
/

CREATE TABLE TEL_URL_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE VARCHAR2(50),
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE VARCHAR2(50)
)
/

CREATE TABLE TS_DATATYPE (
	ID NUMBER(8) NOT NULL,
	VALUE1_VALUE DATE,
	VALUE2_NULL_FLAVOR VARCHAR2(50),
	VALUE2_VALUE DATE
)
/


ALTER TABLE AD_AD_DATATYPE_VALUE9 ADD CONSTRAINT PK_AD_AD_DATATYPE_VALUE9
	PRIMARY KEY (AD_DATATYPE_ID, AD_DATATYPE_VALUE9_ID)
/

ALTER TABLE AD_DATATYPE ADD CONSTRAINT PK_AD_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE AD_DATATYPE_VALUE8 ADD CONSTRAINT PK_AD_DATATYPE_VALUE8
	PRIMARY KEY (ID)
/

ALTER TABLE AD_DATATYPE_VALUE9 ADD CONSTRAINT PK_AD_DATATYPE_VALUE9
	PRIMARY KEY (ID)
/

ALTER TABLE BL_DATATYPE ADD CONSTRAINT PK_BL_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE BL_NONNULL_DATATYPE ADD CONSTRAINT PK_BL_NONNULL_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE CD_CD_DATATYPE_VALUE8 ADD CONSTRAINT PK_CD_CD_DATATYPE_VALUE8
	PRIMARY KEY (CD_DATA_TYPE_ID, CD_DATATYPE_VALUE8_ID)
/

ALTER TABLE CD_DATATYPE ADD CONSTRAINT PK_CD_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE CD_DATATYPE_VALUE6 ADD CONSTRAINT PK_CD_DATATYPE6
	PRIMARY KEY (CD_DATATYPE_ID)
/

ALTER TABLE CD_DATATYPE_VALUE7 ADD CONSTRAINT PK_CD_DATATYPE_VALUE7
	PRIMARY KEY (ID)
/

ALTER TABLE CD_DATATYPE_VALUE8 ADD CONSTRAINT PK_CD_DATATYPE_VALUE8
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_AD_DATATYPE ADD CONSTRAINT PK_DSET_AD_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_AD_DSET_AD_VALUE8 ADD CONSTRAINT PK_DSER_AD_DSET_AD_VALUE8
	PRIMARY KEY (DSET_AD_DATATYPE_ID, DSET_AD_VALUE8_ID)
/

ALTER TABLE DSET_AD_VALUE7 ADD CONSTRAINT PK_AD_DATATYPE_VALUE7
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_AD_VALUE8 ADD CONSTRAINT PK_DSET_AD_VALUE8
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_CD ADD CONSTRAINT PK_DSET_CD
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_CD_CD_VALUE7 ADD CONSTRAINT PK_DSET_CD_CD_VALUE7
	PRIMARY KEY (DSET_CD_ID, DSET_CD_VALUE7_ID)
/

ALTER TABLE DSET_CD_VALUE1 ADD CONSTRAINT PK_DSET_CD_VALUE1
	PRIMARY KEY (DSET_CD_ID)
/

ALTER TABLE DSET_CD_VALUE2 ADD CONSTRAINT PK_DSET_CD_VALUE2
	PRIMARY KEY (DSET_CD_ID)
/

ALTER TABLE DSET_CD_VALUE3 ADD CONSTRAINT PK_DSET_CD_VALUE3
	PRIMARY KEY (DSET_CD_ID)
/

ALTER TABLE DSET_CD_VALUE4 ADD CONSTRAINT PK_DSET_CD_VALUE4
	PRIMARY KEY (DSET_CD_ID)
/

ALTER TABLE DSET_CD_VALUE5 ADD CONSTRAINT PK_DSET_CD_VALUE5
	PRIMARY KEY (DSET_CD_ID)
/

ALTER TABLE DSET_CD_VALUE6 ADD CONSTRAINT PK_DSET_CD_VALUE6
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_CD_VALUE7 ADD CONSTRAINT PK_DSET_CD_VALUE7
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_EN ADD CONSTRAINT PK_DSET_EN_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_EN_VALUE1 ADD CONSTRAINT PK_EN_DATATYPE_VALUE1
	PRIMARY KEY (DSET_EN_DATATYPE_ID)
/

ALTER TABLE DSET_EN_VALUE2 ADD CONSTRAINT PK_EN_DATATYPE_VALUE2
	PRIMARY KEY (DSET_EN_DATATYPE_ID)
/

ALTER TABLE DSET_EN_VALUE3 ADD CONSTRAINT PK_EN_DATATYPE_VALUE3
	PRIMARY KEY (DSET_EN_DATATYPE_ID)
/

ALTER TABLE DSET_EN_VALUE4 ADD CONSTRAINT PK_EN_DATATYPE_VALUE4
	PRIMARY KEY (DSET_EN_DATATYPE_ID)
/

ALTER TABLE DSET_EN_VALUE5 ADD CONSTRAINT PK_EN_DATATYPE_VALUE5
	PRIMARY KEY (DSET_EN_DATATYPE_ID)
/

ALTER TABLE DSET_EN_VALUE6 ADD CONSTRAINT PK_EN_DATATYPE_VALUE6
	PRIMARY KEY (DSET_EN_DATATYPE_ID)
/

ALTER TABLE DSET_EN_VALUE7 ADD CONSTRAINT PK_EN_DATATYPE_VALUE7
	PRIMARY KEY (DSET_EN_DATATYPE_ID)
/

ALTER TABLE DSET_II ADD CONSTRAINT PK_DsetII
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_II_II_VALUE6 ADD CONSTRAINT PK_DSET_II_II_VALUE6
	PRIMARY KEY (DSET_II_ID, DSET_II_VALUE6_ID)
/

ALTER TABLE DSET_II_VALUE1 ADD CONSTRAINT PK_DSET_II_VALUE1
	PRIMARY KEY (DSET_II_ID)
/

ALTER TABLE DSET_II_VALUE2 ADD CONSTRAINT PK_DSET_II_VALUE2
	PRIMARY KEY (DSET_II_ID)
/

ALTER TABLE DSET_II_VALUE3 ADD CONSTRAINT PK_DSET_II_VALUE3
	PRIMARY KEY (DSET_II_ID)
/

ALTER TABLE DSET_II_VALUE4 ADD CONSTRAINT PK_DSET_II_VALUE4
	PRIMARY KEY (DSET_II_ID)
/

ALTER TABLE DSET_II_VALUE5 ADD CONSTRAINT PK_DSET_II_VALUE5
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_II_VALUE6 ADD CONSTRAINT PK_DSET_II_VALUE6
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_TEL ADD CONSTRAINT PK_DSET_TEL
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_TEL_EMAIL ADD CONSTRAINT PK_DSET_TEL_EMAIL
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_TEL_EMAIL_VALUE1 ADD CONSTRAINT PK_DSET_TEL_EMAIL_VALUE1
	PRIMARY KEY (DSET_TEL_EMAIL_ID)
/

ALTER TABLE DSET_TEL_PERSON ADD CONSTRAINT PK_DSET_TEL_PERSON
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_TEL_PERSON_VALUE1 ADD CONSTRAINT PK_DSET_TEL_PERSON_VALUE1
	PRIMARY KEY (DSET_TEL_PERSON_ID)
/

ALTER TABLE DSET_TEL_PHONE ADD CONSTRAINT PK_DSET_TEL_PHONE
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_TEL_PHONE_VALUE1 ADD CONSTRAINT PK_DSET_TEL_PHONE_VALUE1
	PRIMARY KEY (DSET_TEL_PHONE_ID)
/

ALTER TABLE DSET_TEL_TEL_VALUE_3 ADD CONSTRAINT PK_DSET_TEL_TEL_VALUE_3
	PRIMARY KEY (DSET_TEL_ID, DSET_TEL_VALUE3_ID)
/

ALTER TABLE DSET_TEL_URL ADD CONSTRAINT PK_DSET_TEL_URL
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_TEL_URL_VALUE1 ADD CONSTRAINT PK_DSET_TEL_URL_VALUE1
	PRIMARY KEY (DSET_TEL_URL_ID)
/

ALTER TABLE DSET_TEL_VALUE1 ADD CONSTRAINT PK_DSET_TEL_VALUE1
	PRIMARY KEY (DSET_TEL_ID)
/

ALTER TABLE DSET_TEL_VALUE2 ADD CONSTRAINT PK_DSET_TEL_VALUE2
	PRIMARY KEY (ID)
/

ALTER TABLE DSET_TEL_VALUE3 ADD CONSTRAINT PK_DSET_TEL_VALUE3
	PRIMARY KEY (ID)
/

ALTER TABLE ED_DATATYPE ADD CONSTRAINT PK_ED_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE ED_TEXT_DATATYPE ADD CONSTRAINT PK_ED_TEXT_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE EN_DATATYPE ADD CONSTRAINT PK_EN_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE EN_ON_DATATYPE ADD CONSTRAINT PK_EN_ON_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE EN_PN_DATATYPE ADD CONSTRAINT PK_EN_PN_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE II_DATATYPE ADD CONSTRAINT PK_II_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE INT_DATATYPE ADD CONSTRAINT PK_INT_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE IVL_INT ADD CONSTRAINT PK_IVLINT
	PRIMARY KEY (ID)
/

ALTER TABLE IVL_PQ ADD CONSTRAINT PK_IVL_PQ
	PRIMARY KEY (ID)
/

ALTER TABLE IVL_PQV ADD CONSTRAINT PK_IVL_PQV
	PRIMARY KEY (ID)
/

ALTER TABLE PQ_DATATYPE ADD CONSTRAINT PK_PQ_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE PQV_DATATYPE ADD CONSTRAINT PK_PQV_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE REAL_DATATYPE ADD CONSTRAINT PK_REAL_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE SC_DATATYPE ADD CONSTRAINT PK_SC_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE ST_DATATYPE ADD CONSTRAINT PK_ST
	PRIMARY KEY (ID)
/

ALTER TABLE ST_NT_DATATYPE ADD CONSTRAINT PK_ST_NT_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE TEL_DATATYPE ADD CONSTRAINT PK_TEL_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE TEL_EMAIL_DATATYPE ADD CONSTRAINT PK_TEL_EMAIl_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE TEL_PERSON_DATATYPE ADD CONSTRAINT PK_TEL_PERSON_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE TEL_PHONE_DATATYPE ADD CONSTRAINT PK_TEL_PHONE_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE TEL_URL_DATATYPE ADD CONSTRAINT PK_TEL_URL_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE TS_DATATYPE ADD CONSTRAINT PK_TS_DATATYPE
	PRIMARY KEY (ID)
/

ALTER TABLE AD_AD_DATATYPE_VALUE9 ADD CONSTRAINT FK_AD_AD_DATATYP_AD_DATATYPE_V
	FOREIGN KEY (AD_DATATYPE_VALUE9_ID) REFERENCES AD_DATATYPE_VALUE9 (ID)
/

ALTER TABLE AD_AD_DATATYPE_VALUE9 ADD CONSTRAINT FK_AD_AD_DATATYPE__AD_DATATYPE
	FOREIGN KEY (AD_DATATYPE_ID) REFERENCES AD_DATATYPE (ID)
/

ALTER TABLE AD_DATATYPE ADD CONSTRAINT FK_AD_DATATYPE_VALUE8
	FOREIGN KEY (AD_DATATYPE_VALUE8_ID) REFERENCES AD_DATATYPE_VALUE8 (ID)
/

ALTER TABLE AD_DATATYPE_VALUE7 ADD CONSTRAINT FK_AD_DATATYPE_VAL_AD_DATATYPE
	FOREIGN KEY (AD_DATATYPE_ID) REFERENCES AD_DATATYPE (ID)
/

ALTER TABLE CD_CD_DATATYPE_VALUE8 ADD CONSTRAINT FK_CD_CD_DATATYP_CD_DATATYPE_V
	FOREIGN KEY (CD_DATATYPE_VALUE8_ID) REFERENCES CD_DATATYPE_VALUE8 (ID)
/

ALTER TABLE CD_CD_DATATYPE_VALUE8 ADD CONSTRAINT FK_CD_CD_DATATYPE__CD_DATATYPE
	FOREIGN KEY (CD_DATA_TYPE_ID) REFERENCES CD_DATATYPE (ID)
/

ALTER TABLE CD_DATATYPE ADD CONSTRAINT FK_CD_DATATYPE_VALUE7
	FOREIGN KEY (CD_DATATYPE_VALUE7_ID) REFERENCES CD_DATATYPE_VALUE7 (ID)
/

ALTER TABLE CD_DATATYPE_VALUE6 ADD CONSTRAINT FK_CD_DATATYPE_VAL_CD_DATAT
	FOREIGN KEY (CD_DATATYPE_ID) REFERENCES CD_DATATYPE (ID)
/

ALTER TABLE DSET_AD_DSET_AD_VALUE8 ADD CONSTRAINT FK_DSER_AD_DSET__DSET_AD_DATA
	FOREIGN KEY (DSET_AD_DATATYPE_ID) REFERENCES DSET_AD_DATATYPE (ID)
/

ALTER TABLE DSET_AD_DSET_AD_VALUE8 ADD CONSTRAINT FK_DSER_AD_DSET__DSET_AD_VALU
	FOREIGN KEY (DSET_AD_VALUE8_ID) REFERENCES DSET_AD_VALUE8 (ID)
/

ALTER TABLE DSET_AD_VALUE1 ADD CONSTRAINT FK_DSER_AD_DATATY_VAL_AD_DA
	FOREIGN KEY (DSET_AD_DATATYPE_ID) REFERENCES DSET_AD_DATATYPE (ID)
/

ALTER TABLE DSET_AD_VALUE2 ADD CONSTRAINT FK_DSER_AD_DATAT_VAL_AD_DATAT
	FOREIGN KEY (DSET_AD_DATATYPE_ID) REFERENCES DSET_AD_DATATYPE (ID)
/

ALTER TABLE DSET_AD_VALUE3 ADD CONSTRAINT FK_DSER_AD_DATAT_VAL_AD3
	FOREIGN KEY (DSET_AD_DATATYPE_ID) REFERENCES DSET_AD_DATATYPE (ID)
/

ALTER TABLE DSET_AD_VALUE4 ADD CONSTRAINT FK_DSER_AD_TYPE_VAL_AD4
	FOREIGN KEY (DSET_AD_DATATYPE_ID) REFERENCES DSET_AD_DATATYPE (ID)
/

ALTER TABLE DSET_AD_VALUE5 ADD CONSTRAINT FK_DSER_AD_DATAT_VAL_AD5
	FOREIGN KEY (DSET_AD_DATATYPE_ID) REFERENCES DSET_AD_DATATYPE (ID)
/

ALTER TABLE DSET_AD_VALUE6 ADD CONSTRAINT FK_DSER_AD_TYPE_VAL_AD6
	FOREIGN KEY (DSET_AD_DATATYPE_ID) REFERENCES DSET_AD_DATATYPE (ID)
/

ALTER TABLE DSET_AD_VALUE7 ADD CONSTRAINT FK_DSET_AD_VALUE_DSET_AD7
	FOREIGN KEY (DSET_AD_DATATYPE_ID) REFERENCES DSET_AD_DATATYPE (ID)
/

ALTER TABLE DSET_CD_CD_VALUE7 ADD CONSTRAINT FK_DSET_CD_CD_VA_DSET_CD5
	FOREIGN KEY (DSET_CD_VALUE7_ID) REFERENCES DSET_CD_VALUE7 (ID)
/

ALTER TABLE DSET_CD_CD_VALUE7 ADD CONSTRAINT FK_DSET_CD_CD_VALUE7_DSET_CD
	FOREIGN KEY (DSET_CD_ID) REFERENCES DSET_CD (ID)
/

ALTER TABLE DSET_CD_VALUE1 ADD CONSTRAINT FK_DSET_CD_VALUE1_DSET_CD
	FOREIGN KEY (DSET_CD_ID) REFERENCES DSET_CD (ID)
/

ALTER TABLE DSET_CD_VALUE2 ADD CONSTRAINT FK_DSET_CD_VALUE2_DSET_CD
	FOREIGN KEY (DSET_CD_ID) REFERENCES DSET_CD (ID)
/

ALTER TABLE DSET_CD_VALUE3 ADD CONSTRAINT FK_DSET_CD_VALUE3_DSET_CD
	FOREIGN KEY (DSET_CD_ID) REFERENCES DSET_CD (ID)
/

ALTER TABLE DSET_CD_VALUE4 ADD CONSTRAINT FK_DSET_CD_VALUE4_DSET_CD
	FOREIGN KEY (DSET_CD_ID) REFERENCES DSET_CD (ID)
/

ALTER TABLE DSET_CD_VALUE5 ADD CONSTRAINT FK_DSET_CD_VALUE5_DSET_CD
	FOREIGN KEY (DSET_CD_ID) REFERENCES DSET_CD (ID)
/

ALTER TABLE DSET_CD_VALUE6 ADD CONSTRAINT FK_DSET_CD_VALUE6_DSET_CD
	FOREIGN KEY (DSET_CD_ID) REFERENCES DSET_CD (ID)
/

ALTER TABLE DSET_EN_VALUE1 ADD CONSTRAINT FK_EN_TYPE_VAL_EN_TYPE
	FOREIGN KEY (DSET_EN_DATATYPE_ID) REFERENCES DSET_EN (ID)
/

ALTER TABLE DSET_EN_VALUE2 ADD CONSTRAINT FK_EN_TYPE_VAL2_EN_TYPE
	FOREIGN KEY (DSET_EN_DATATYPE_ID) REFERENCES DSET_EN (ID)
/

ALTER TABLE DSET_EN_VALUE3 ADD CONSTRAINT FK_EN_TYPE_VAL3_EN_TYPE
	FOREIGN KEY (DSET_EN_DATATYPE_ID) REFERENCES DSET_EN (ID)
/

ALTER TABLE DSET_EN_VALUE4 ADD CONSTRAINT FK_EN_DATATYPE_VAL4_EN_DATAT
	FOREIGN KEY (DSET_EN_DATATYPE_ID) REFERENCES DSET_EN (ID)
/

ALTER TABLE DSET_EN_VALUE6 ADD CONSTRAINT FK_EN_DATATYPE_VAL6_EN_DATAT
	FOREIGN KEY (DSET_EN_DATATYPE_ID) REFERENCES DSET_EN (ID)
/

ALTER TABLE DSET_EN_VALUE7 ADD CONSTRAINT FK_EN_DATATYPE_VAL7_EN_DATAT
	FOREIGN KEY (DSET_EN_DATATYPE_ID) REFERENCES DSET_EN (ID)
/

ALTER TABLE DSET_II_II_VALUE6 ADD CONSTRAINT FK_DSET_II_II_VA_DSET_II_VAL
	FOREIGN KEY (DSET_II_VALUE6_ID) REFERENCES DSET_II_VALUE6 (ID)
/

ALTER TABLE DSET_II_II_VALUE6 ADD CONSTRAINT FK_DSET_II_II_VALUE6_DSET_II
	FOREIGN KEY (DSET_II_ID) REFERENCES DSET_II (ID)
/

ALTER TABLE DSET_II_VALUE1 ADD CONSTRAINT FK_DSET_II_VALUE1_DsetII
	FOREIGN KEY (DSET_II_ID) REFERENCES DSET_II (ID)
/

ALTER TABLE DSET_II_VALUE2 ADD CONSTRAINT FK_DSET_II_VALUE2_DsetII
	FOREIGN KEY (DSET_II_ID) REFERENCES DSET_II (ID)
/

ALTER TABLE DSET_II_VALUE3 ADD CONSTRAINT FK_DSET_II_VALUE3_DsetII
	FOREIGN KEY (DSET_II_ID) REFERENCES DSET_II (ID)
/

ALTER TABLE DSET_II_VALUE4 ADD CONSTRAINT FK_DSET_II_VALUE4_DsetII
	FOREIGN KEY (DSET_II_ID) REFERENCES DSET_II (ID)
/

ALTER TABLE DSET_II_VALUE5 ADD CONSTRAINT FK_DSET_II_VALUE5_DSET_II
	FOREIGN KEY (DSET_II_ID) REFERENCES DSET_II (ID)
/

ALTER TABLE DSET_TEL_EMAIL_VALUE1 ADD CONSTRAINT FK_DSET_TEL_EMAI_DSET_TEL_EMA
	FOREIGN KEY (DSET_TEL_EMAIL_ID) REFERENCES DSET_TEL_EMAIL (ID)
/

ALTER TABLE DSET_TEL_EMAIL_VALUE2 ADD CONSTRAINT FK_TEL_EMAIL_VAL_DSET_TEL_EMA
	FOREIGN KEY (DSET_TEL_EMAIL_ID) REFERENCES DSET_TEL_EMAIL (ID)
/

ALTER TABLE DSET_TEL_PERSON_VALUE1 ADD CONSTRAINT FK_DSET_TEL_PERS_DSET_TEL_PER
	FOREIGN KEY (DSET_TEL_PERSON_ID) REFERENCES DSET_TEL_PERSON (ID)
/

ALTER TABLE DSET_TEL_PHONE_VALUE1 ADD CONSTRAINT FK_DSET_TEL_PHON_DSET_TEL_PHO
	FOREIGN KEY (DSET_TEL_PHONE_ID) REFERENCES DSET_TEL_PHONE (ID)
/

ALTER TABLE DSET_TEL_TEL_VALUE_3 ADD CONSTRAINT FK_DSET_TEL_TEL__DSET_TEL_VAL
	FOREIGN KEY (DSET_TEL_VALUE3_ID) REFERENCES DSET_TEL_VALUE3 (ID)
/

ALTER TABLE DSET_TEL_TEL_VALUE_3 ADD CONSTRAINT FK_DSET_TEL_TEL_VALU_DSET_TEL
	FOREIGN KEY (DSET_TEL_ID) REFERENCES DSET_TEL (ID)
/

ALTER TABLE DSET_TEL_URL_VALUE1 ADD CONSTRAINT FK_DSET_TEL_URL_V_DSET_TEL_URL
	FOREIGN KEY (DSET_TEL_URL_ID) REFERENCES DSET_TEL_URL (ID)
/

ALTER TABLE DSET_TEL_VALUE1 ADD CONSTRAINT FK_DSET_TEL_VALUE1_DSET_TEL
	FOREIGN KEY (DSET_TEL_ID) REFERENCES DSET_TEL (ID)
/

ALTER TABLE DSET_TEL_VALUE2 ADD CONSTRAINT FK_DSET_TEL_VALUE2_DSET_TEL
	FOREIGN KEY (DSET_TEL_ID) REFERENCES DSET_TEL (ID)
/


INSERT INTO AD_DATATYPE (ID,VALUE1_AL_VALUE) values (1111, null)
/
INSERT INTO AD_DATATYPE (ID,VALUE1_AL_VALUE) values (1112,'2115 E Jefferson Street')
/
INSERT INTO AD_DATATYPE (ID,VALUE2_DAL_VALUE,VALUE2_DAL_CODE) values (1113,null,null)
/
INSERT INTO AD_DATATYPE (ID,VALUE2_DAL_VALUE,VALUE2_DAL_CODE) values (1114,'5th Floor',null)
/
INSERT INTO AD_DATATYPE (ID,VALUE2_DAL_VALUE,VALUE2_DAL_CODE) values (1115,'5th Floor','NCI5')
/
INSERT INTO AD_DATATYPE (ID,VALUE3_AL_VALUE ,VALUE3_AL_CODE ,VALUE3_AL_CODESYSTEM) values(1116,null,null,null)
/
INSERT INTO AD_DATATYPE (ID,VALUE3_AL_VALUE ,VALUE3_AL_CODE ,VALUE3_AL_CODESYSTEM) values(1117,'2115 E Jefferson Street',null,null)
/
INSERT INTO AD_DATATYPE (ID,VALUE3_AL_VALUE ,VALUE3_AL_CODE ,VALUE3_AL_CODESYSTEM) values(1118,'2115 E Jefferson Street','NCI',null)
/
INSERT INTO AD_DATATYPE (ID,VALUE3_AL_VALUE ,VALUE3_AL_CODE ,VALUE3_AL_CODESYSTEM) values(1119,'2115 E Jefferson Street','NCI','codeSystem')
/
INSERT INTO AD_DATATYPE (ID,VALUE4_AL1_VALUE, VALUE4_AL2_VALUE ,VALUE4_AL1_CODE ,VALUE4_AL2_CODE,VALUE4_AL1_CODESYSTEM,VALUE4_AL2_CODESYSTEM)
	   values(1120,null,null,null,null,null,null)
/
INSERT INTO AD_DATATYPE (ID,VALUE4_AL1_VALUE, VALUE4_AL2_VALUE ,VALUE4_AL1_CODE ,VALUE4_AL2_CODE,VALUE4_AL1_CODESYSTEM,VALUE4_AL2_CODESYSTEM)
	   values(1121,'2115 E Jefferson Street',null,'NCI',null,'codeSystem',null)
/
INSERT INTO AD_DATATYPE (ID,VALUE4_AL1_VALUE, VALUE4_AL2_VALUE ,VALUE4_AL1_CODE ,VALUE4_AL2_CODE,VALUE4_AL1_CODESYSTEM,VALUE4_AL2_CODESYSTEM)
	   values(1122,'2115 E Jefferson Street','2119 E Jefferson Street','NCI','NCI-DC','codeSystem','codeSystem2')
/

INSERT INTO AD_DATATYPE (ID,VALUE5_AL_VALUE) values(1123,null)
/
INSERT INTO AD_DATATYPE (ID,VALUE5_AL_VALUE) values(1124,'AD value5')
/
INSERT INTO AD_DATATYPE (ID,VALUE6_ADL_VALUE,VALUE6_AL_VALUE
		,VALUE6_BNN_VALUE,VALUE6_BNR_VALUE,VALUE6_BNS_VALUE
		,VALUE6_CAR_VALUE,VALUE6_CEN_VALUE  ,VALUE6_CNT_VALUE  ,VALUE6_CPA_VALUE,VALUE6_CTY_VALUE
		,VALUE6_DAL_VALUE ,VALUE6_DEL_VALUE
		,VALUE6_DINSTA_VALUE  ,VALUE6_DINSTQ_VALUE  ,VALUE6_DIR_VALUE ,VALUE6_DMOD_VALUE,VALUE6_DMODID_VALUE
		,VALUE6_INT_VALUE,VALUE6_POB_VALUE,VALUE6_PRE_VALUE,VALUE6_SAL_VALUE,VALUE6_STA_VALUE,VALUE6_STB_VALUE
		,VALUE6_STR_VALUE,VALUE6_STTYP_VALUE,VALUE6_UNID_VALUE,VALUE6_UNIT_VALUE,VALUE6_ZIP_VALUE,VALUE6_ADL_CODE
		,VALUE6_BNS_CODE,VALUE6_BNS_CODESYSTEM,VALUE6_DAL_CODE,VALUE6_DAL_CODESYSTEM,VALUE6_INT_CODE,VALUE6_INT_CODESYSTEM
		,VALUE6_STB_CODE,VALUE6_STB_CODESYSTEM,VALUE6_ZIP_CODESYSTEM,VALUE6_ZIP_CODE
	) values (1125,null,null,null,null,null,null,null,null,null,null,null ,null,null  ,null  ,null ,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null)
/
INSERT INTO AD_DATATYPE (ID,VALUE6_ADL_VALUE,VALUE6_AL_VALUE
		,VALUE6_BNN_VALUE,VALUE6_BNR_VALUE,VALUE6_BNS_VALUE
		,VALUE6_CAR_VALUE,VALUE6_CEN_VALUE  ,VALUE6_CNT_VALUE  ,VALUE6_CPA_VALUE,VALUE6_CTY_VALUE
		,VALUE6_DAL_VALUE ,VALUE6_DEL_VALUE
		,VALUE6_DINSTA_VALUE  ,VALUE6_DINSTQ_VALUE  ,VALUE6_DIR_VALUE ,VALUE6_DMOD_VALUE,VALUE6_DMODID_VALUE
		,VALUE6_INT_VALUE,VALUE6_POB_VALUE,VALUE6_PRE_VALUE,VALUE6_SAL_VALUE,VALUE6_STA_VALUE,VALUE6_STB_VALUE
		,VALUE6_STR_VALUE,VALUE6_STTYP_VALUE,VALUE6_UNID_VALUE,VALUE6_UNIT_VALUE,VALUE6_ZIP_VALUE,VALUE6_ADL_CODE
		,VALUE6_BNS_CODE,VALUE6_BNS_CODESYSTEM,VALUE6_DAL_CODE,VALUE6_DAL_CODESYSTEM,VALUE6_INT_CODE,VALUE6_INT_CODESYSTEM
		,VALUE6_STB_CODE,VALUE6_STB_CODESYSTEM,VALUE6_ZIP_CODESYSTEM,VALUE6_ZIP_CODE
	) values (1126,'VALUE6_ADL_VALUE','VALUE6_AL_VALUE','VALUE6_BNN_VALUE','VALUE6_BNR_VALUE','VALUE6_BNS_VALUE',
'VALUE6_CAR_VALUE','VALUE6_CEN_VALUE  ','VALUE6_CNT_VALUE  ','VALUE6_CPA_VALUE','VALUE6_CTY_VALUE',
'VALUE6_DAL_VALUE ','VALUE6_DEL_VALUE','VALUE6_DINSTA_VALUE  ','VALUE6_DINSTQ_VALUE  ','VALUE6_DIR_VALUE ',
'VALUE6_DMOD_VALUE','VALUE6_DMODID_VALUE',
'VALUE6_INT_VALUE','VALUE6_POB_VALUE','VALUE6_PRE_VALUE','VALUE6_SAL_VALUE','VALUE6_STA_VALUE','VALUE6_STB_VALUE',
'VALUE6_STR_VALUE','VALUE6_STTYP_VALUE','VALUE6_UNID_VALUE','VALUE6_UNIT_VALUE','VALUE6_ZIP_VALUE','VALUE6_ADL_CODE',
'VALUE6_BNS_CODE','VALUE6_BNS_CODESYSTEM','VALUE6_DAL_CODE','VALUE6_DAL_CODESYSTEM','VALUE6_INT_CODE',
'VALUE6_INT_CODESYSTEM','VALUE6_STB_CODE','VALUE6_STB_CODESYSTEM','VALUE6_ZIP_CODESYSTEM','VALUE6_ZIP_CODE')
/

INSERT INTO AD_DATATYPE (ID) values ( 1127)
/
INSERT INTO AD_DATATYPE_VALUE7 (AD_DATATYPE_ID,AL_VALUE,AL_CODE,AL_CODESYSTEM,DAL_CODE,DAL_VALUE,DAL_CODESYSTEM,CTY_VALUE,CTY_CODE,CTY_CODESYSTEM)
values (1127,null,null,null,null,null,null,null,null,null)
/

INSERT INTO AD_DATATYPE (ID) values ( 1128)
/
INSERT INTO AD_DATATYPE_VALUE7 (AD_DATATYPE_ID,AL_VALUE,AL_CODE,AL_CODESYSTEM,DAL_CODE,DAL_VALUE,DAL_CODESYSTEM,CTY_VALUE,CTY_CODE,CTY_CODESYSTEM)
values (1128,'AL_VALUE','AL_CODE','AL_CODESYSTEM','DAL_CODE','DAL_VALUE','DAL_CODESYSTEM','CTY_VALUE','CTY_CODE','CTY_CODESYSTEM')
/
INSERT INTO BL_DATATYPE (ID,VALUE1_VALUE) values (2220,null)
/
INSERT INTO BL_DATATYPE (ID,VALUE1_VALUE) values (2221,'1')
/
INSERT INTO BL_DATATYPE (ID,VALUE2_NULL_FLAVOR,VALUE2_VALUE) values (2222,'NI',null)
/
INSERT INTO BL_DATATYPE (ID,VALUE2_NULL_FLAVOR,VALUE2_VALUE) values (2223,null,'0')
/

INSERT INTO BL_NONNULL_DATATYPE (ID,VALUE1_VALUE) values (2224,'0')
/
INSERT INTO BL_NONNULL_DATATYPE (ID,VALUE1_VALUE) values (2225,'1')
/


INSERT INTO CD_DATATYPE (ID,VALUE1_CODE) values (10,'CODE1' )
/
INSERT INTO CD_DATATYPE (ID,VALUE2_CODE,VALUE2_NULL_FLAVOR) values (11, 'CODE1','NI')
/
INSERT INTO CD_DATATYPE (ID,VALUE3_CODE) values (12,'CODE' )
/
INSERT INTO CD_DATATYPE (ID,VALUE4_NULL_FLAVOR,VALUE4_CODE,VALUE4_CODE_SYSTEM,VALUE4_CODE_SYSTEM_VERSION,VALUE4_CODE_SYSTEM_NAME,
	   VALUE4_DISPLAY_NULL_FLAVOR,VALUE4_DISPLAY_VALUE,VALUE4_ORIG_TXT_NULL_FLAVOR,
	   VALUE4_ORIG_TXT_DESCRIPTION,VALUE4_ORIG_TXT_VALUE,
	   VALUE5_NULL_FLAVOR,VALUE5_CODE,VALUE5_CODE_SYSTEM,VALUE5_CODE_SYSTEM_NAME,VALUE5_CODE_SYSTEM_VERSION,
	   VALUE5_DISPLAY_NULL_FLAVOR,VALUE5_DISPLAY_VALUE,VALUE5_ORIG_TXT_NULL_FLAVOR,
	   VALUE5_ORIG_TXT_DESCRIPTION,VALUE5_ORIG_TXT_VALUE
	   ) values (
	   13,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null)
/
INSERT INTO CD_DATATYPE (ID,VALUE4_NULL_FLAVOR,VALUE4_CODE,VALUE4_CODE_SYSTEM,VALUE4_CODE_SYSTEM_VERSION,VALUE4_CODE_SYSTEM_NAME,
	   VALUE4_DISPLAY_NULL_FLAVOR,VALUE4_DISPLAY_VALUE,VALUE4_ORIG_TXT_NULL_FLAVOR,
	   VALUE4_ORIG_TXT_DESCRIPTION,VALUE4_ORIG_TXT_VALUE,
	   VALUE5_NULL_FLAVOR,VALUE5_CODE,VALUE5_CODE_SYSTEM,VALUE5_CODE_SYSTEM_NAME,VALUE5_CODE_SYSTEM_VERSION,
	   VALUE5_DISPLAY_NULL_FLAVOR,VALUE5_DISPLAY_VALUE,VALUE5_ORIG_TXT_NULL_FLAVOR,
	   VALUE5_ORIG_TXT_DESCRIPTION,VALUE5_ORIG_TXT_VALUE
	   ) values (
	   14,'NI','VALUE4_CODE','VALUE4_CODE_SYSTEM','1.2','VALUE4_CODE_SYSTEM_NAME',
	   'UNK','VALUE4_DISPLAY_VALUE','UNK',
	   'VALUE4_ORIG_TXT_DESCRIPTION','VALUE4_ORIG_TXT_VALUE',
	   'UNK','VALUE5_CODE','VALUE5_CODE_SYSTEM', 'VALUE5_CODE_SYSTEM_NAME','1.2',
	   'UNK','VALUE5_DISPLAY_VALUE','UNK',
	   'VALUE5_ORIG_TXT_DESCRIPTION','VALUE5_ORIG_TXT_VALUE')
/


INSERT INTO EN_DATATYPE (ID,VALUE1_PN_VALUE) values (20,null  )
/
INSERT INTO EN_DATATYPE (ID,VALUE1_PN_VALUE) values (21,'Mr. John Doe Sr.')
/
INSERT INTO EN_DATATYPE (ID,VALUE2_PN_VALUE,VALUE2_PN_CODE) values (22,null,null)
/
INSERT INTO EN_DATATYPE (ID,VALUE2_PN_VALUE,VALUE2_PN_CODE) values (23,'Mr. John Doe Jr.',null)
/
INSERT INTO EN_DATATYPE (ID,VALUE2_PN_VALUE,VALUE2_PN_CODE) values (24,'Mr. John Doe Jr.','JDJ')
/

INSERT INTO EN_DATATYPE (ID,VALUE3_PN_VALUE,VALUE3_PN_CODE,VALUE3_PN_CODE_SYSTEM,VALUE3_PN_CODE_SYSTEM_VERSION)values
	(25,null,null,null,null)
/
INSERT INTO EN_DATATYPE (ID,VALUE3_PN_VALUE,VALUE3_PN_CODE,VALUE3_PN_CODE_SYSTEM,VALUE3_PN_CODE_SYSTEM_VERSION)values
	(26,'Mrs. Sarah Doe',null,null,null)
/
INSERT INTO EN_DATATYPE (ID,VALUE3_PN_VALUE,VALUE3_PN_CODE,VALUE3_PN_CODE_SYSTEM,VALUE3_PN_CODE_SYSTEM_VERSION)values
	(27,'Mrs. Sarah Doe','MSD',null,null)
/
INSERT INTO EN_DATATYPE (ID,VALUE3_PN_VALUE,VALUE3_PN_CODE,VALUE3_PN_CODE_SYSTEM,VALUE3_PN_CODE_SYSTEM_VERSION)values
	(28,'Mrs. Sarah Doe','MSD','VALUE3_PN_CODE_SYSTEM',null)
/
INSERT INTO EN_DATATYPE (ID,VALUE3_PN_VALUE,VALUE3_PN_CODE,VALUE3_PN_CODE_SYSTEM,VALUE3_PN_CODE_SYSTEM_VERSION)values
	(29,'Mrs. Sarah Doe','MSD','VALUE3_PN_CODE_SYSTEM','1.3')
/

INSERT INTO EN_DATATYPE (ID,VALUE4_PN_VALUE,VALUE4_PN_ENPQ)values (30,null,null)
/
INSERT INTO EN_DATATYPE (ID,VALUE4_PN_VALUE,VALUE4_PN_ENPQ)values (31,'VALUE4_PN_VALUE','VALUE4_PN_ENPQ')
/

INSERT INTO EN_DATATYPE (ID,
	VALUE5_PN_VALUE,VALUE5_PN2_VALUE,VALUE5_PN_CODE,VALUE5_PN2_CODE,VALUE5_PN_CODE_SYSTEM,VALUE5_PN2_CODE_SYSTEM,
	VALUE5_PN_CODE_SYSTEM_VERSION,VALUE5_PN2_CODE_SYSTEM_VERSION
	)values (32,null,null,null,null,null,null,null,null)
/
INSERT INTO EN_DATATYPE (ID,
	VALUE5_PN_VALUE,VALUE5_PN2_VALUE,VALUE5_PN_CODE,VALUE5_PN2_CODE,VALUE5_PN_CODE_SYSTEM,VALUE5_PN2_CODE_SYSTEM,
	VALUE5_PN_CODE_SYSTEM_VERSION,VALUE5_PN2_CODE_SYSTEM_VERSION
	)values (
	33,'Mr. John Doe III',null,'JDJIII',null,'VALUE5_PN_CODE_SYSTEM',null,'2.1',null)
/
INSERT INTO EN_DATATYPE (ID,
	VALUE5_PN_VALUE,VALUE5_PN2_VALUE,VALUE5_PN_CODE,VALUE5_PN2_CODE,VALUE5_PN_CODE_SYSTEM,VALUE5_PN2_CODE_SYSTEM,
	VALUE5_PN_CODE_SYSTEM_VERSION,VALUE5_PN2_CODE_SYSTEM_VERSION
	)values (
	34,'Mr. John Doe III','Mr. John Doe II','VALUE5_PN_CODE','VALUE5_PN2_CODE','VALUE5_PN_CODE_SYSTEM','VALUE5_PN2_CODE_SYSTEM',
	'2.1','2.2')
/


INSERT INTO EN_DATATYPE (ID,
	VALUE6_PN_VALUE,VALUE6_ON_VALUE,VALUE6_PN_CODE,VALUE6_ON_CODE,VALUE6_PN_CODE_SYSTEM,VALUE6_ON_CODE_SYSTEM,VALUE6_PN_CODE_SYSTEM_VERSION,VALUE6_ON_CODE_SYSTEM_VERSION
	)values (35,null,null,null,null,null,null,null,null)
/
INSERT INTO EN_DATATYPE (ID,
	VALUE6_PN_VALUE,VALUE6_ON_VALUE,VALUE6_PN_CODE,VALUE6_ON_CODE,VALUE6_PN_CODE_SYSTEM,VALUE6_ON_CODE_SYSTEM,VALUE6_PN_CODE_SYSTEM_VERSION,VALUE6_ON_CODE_SYSTEM_VERSION
	)values (
	36,'Mr. John Doe IV',null,'VALUE6_PN_CODE',null,'VALUE6_PN_CODE_SYSTEM',null,'3.1',null)
/
INSERT INTO EN_DATATYPE (ID,
	VALUE6_PN_VALUE,VALUE6_ON_VALUE,VALUE6_PN_CODE,VALUE6_ON_CODE,VALUE6_PN_CODE_SYSTEM,VALUE6_ON_CODE_SYSTEM,VALUE6_PN_CODE_SYSTEM_VERSION,VALUE6_ON_CODE_SYSTEM_VERSION
	)values (
	37,'Mr. John Doe IV','NCI','VALUE6_PN_CODE','VALUE6_ON_CODE','VALUE6_PN_CODE_SYSTEM','VALUE6_ON_CODE_SYSTEM','3.1','VALUE6_ON_CODE_SYSTEM_VERSION')
/

INSERT INTO EN_DATATYPE (ID,VALUE1_PN_VALUE) values (38,null  )
/
INSERT INTO EN_DATATYPE (ID,VALUE1_PN_VALUE) values (39,'Mr. John Doe Sr.')
/

INSERT INTO EN_ON_DATATYPE (ID,VALUE1_ON_VALUE) values (40,null  )
/
INSERT INTO EN_ON_DATATYPE (ID,VALUE1_ON_VALUE) values (41,'NCI')
/


INSERT INTO II_DATATYPE (ID,VALUE1_EXTENSION ) values (110,null)
/
INSERT INTO II_DATATYPE (ID,VALUE1_EXTENSION ) values (111,'II_Extension' )
/

INSERT INTO II_DATATYPE (ID,VALUE2_NULL_FLAVOR,VALUE2_ROOT,VALUE2_EXTENSION ) values (112,null,null,null)
/
INSERT INTO II_DATATYPE (ID,VALUE2_NULL_FLAVOR,VALUE2_ROOT,VALUE2_EXTENSION ) values (113,'NI', null,null)
/
INSERT INTO II_DATATYPE (ID,VALUE2_NULL_FLAVOR,VALUE2_ROOT,VALUE2_EXTENSION ) values (114,'NI','II_VALUE2_ROOT',null )
/
INSERT INTO II_DATATYPE (ID,VALUE2_NULL_FLAVOR,VALUE2_ROOT,VALUE2_EXTENSION ) values (115,'NI','II_VALUE2_ROOT','II_VALUE2_EXTENSION')
/

INSERT INTO II_DATATYPE (ID,VALUE3_NULL_FLAVOR,VALUE3_EXTENSION,VALUE3_IDENTIFIER_NAME,VALUE3_RELIABILITY,VALUE3_SCOPE,VALUE3_DISPLAYABLE
) values (116,null,null,null,null,null,null)
/
INSERT INTO II_DATATYPE (ID,VALUE3_NULL_FLAVOR,VALUE3_EXTENSION,VALUE3_IDENTIFIER_NAME,VALUE3_RELIABILITY,VALUE3_SCOPE,VALUE3_DISPLAYABLE
) values (117,'UNK' ,null,null,null,null,null)
/
INSERT INTO II_DATATYPE (ID,VALUE3_NULL_FLAVOR,VALUE3_EXTENSION,VALUE3_IDENTIFIER_NAME,VALUE3_RELIABILITY,VALUE3_SCOPE,VALUE3_DISPLAYABLE
) values (118,'UNK','II_VALUE3_EXTENSION',null,null,null,null )
/
INSERT INTO II_DATATYPE (ID,VALUE3_NULL_FLAVOR,VALUE3_EXTENSION,VALUE3_IDENTIFIER_NAME,VALUE3_RELIABILITY,VALUE3_SCOPE,VALUE3_DISPLAYABLE
) values (119,'UNK','II_VALUE3_EXTENSION','II_VALUE3_IDENTIFIER_NAME',null,null,null )
/
INSERT INTO II_DATATYPE (ID,VALUE3_NULL_FLAVOR,VALUE3_EXTENSION,VALUE3_IDENTIFIER_NAME,VALUE3_RELIABILITY,VALUE3_SCOPE,VALUE3_DISPLAYABLE
) values (120,'UNK','II_VALUE3_EXTENSION','II_VALUE3_IDENTIFIER_NAME','ISS', 'BUSN',null)
/
INSERT INTO II_DATATYPE (ID,VALUE3_NULL_FLAVOR,VALUE3_EXTENSION,VALUE3_IDENTIFIER_NAME,VALUE3_RELIABILITY,VALUE3_SCOPE,VALUE3_DISPLAYABLE
) values (121,'UNK','II_VALUE3_EXTENSION','II_VALUE3_IDENTIFIER_NAME','VRF','OBJ','1' )
/

INSERT INTO II_DATATYPE (ID,VALUE4_NULL_FLAVOR,VALUE4_ROOT,VALUE4_EXTENSION,VALUE4_IDENTIFIER_NAME,VALUE4_RELIABILITY,VALUE4_SCOPE,VALUE4_DISPLAYABLE
) values (122,null,null,null,null,null,null,null)
/
INSERT INTO II_DATATYPE (ID,VALUE4_NULL_FLAVOR,VALUE4_ROOT,VALUE4_EXTENSION,VALUE4_IDENTIFIER_NAME,VALUE4_RELIABILITY,VALUE4_SCOPE,VALUE4_DISPLAYABLE
) values (123,'INV','II_VALUE4_ROOT',null,null,null,null,null )
/
INSERT INTO II_DATATYPE (ID,VALUE4_NULL_FLAVOR,VALUE4_ROOT,VALUE4_EXTENSION,VALUE4_IDENTIFIER_NAME,VALUE4_RELIABILITY,VALUE4_SCOPE,VALUE4_DISPLAYABLE
) values (124,'INV','II_VALUE4_ROOT','II_VALUE4_EXTENSION',null,null,null,null)
/
INSERT INTO II_DATATYPE (ID,VALUE4_NULL_FLAVOR,VALUE4_ROOT,VALUE4_EXTENSION,VALUE4_IDENTIFIER_NAME,VALUE4_RELIABILITY,VALUE4_SCOPE,VALUE4_DISPLAYABLE
) values (125,'INV','II_VALUE4_ROOT','II_VALUE4_EXTENSION','II_VALUE4_IDENTIFIER_NAME',null,null,null)
/
INSERT INTO II_DATATYPE (ID,VALUE4_NULL_FLAVOR,VALUE4_ROOT,VALUE4_EXTENSION,VALUE4_IDENTIFIER_NAME,VALUE4_RELIABILITY,VALUE4_SCOPE,VALUE4_DISPLAYABLE
) values (126,'INV','II_VALUE4_ROOT','II_VALUE4_EXTENSION','II_VALUE4_IDENTIFIER_NAME','VRF',null,null)
/
INSERT INTO II_DATATYPE (ID,VALUE4_NULL_FLAVOR,VALUE4_ROOT,VALUE4_EXTENSION,VALUE4_IDENTIFIER_NAME,VALUE4_RELIABILITY,VALUE4_SCOPE,VALUE4_DISPLAYABLE
) values (127,'INV','II_VALUE4_ROOT','II_VALUE4_EXTENSION','II_VALUE4_IDENTIFIER_NAME','UNV','VER',null )
/
INSERT INTO II_DATATYPE (ID,VALUE4_NULL_FLAVOR,VALUE4_ROOT,VALUE4_EXTENSION,VALUE4_IDENTIFIER_NAME,VALUE4_RELIABILITY,VALUE4_SCOPE,VALUE4_DISPLAYABLE
) values (128,'INV','II_VALUE4_ROOT','II_VALUE4_EXTENSION','II_VALUE4_IDENTIFIER_NAME','UNV','VW','0')
/


INSERT INTO INT_DATATYPE(ID,VALUE1_VALUE ) values (220,null)
/

INSERT INTO INT_DATATYPE(ID,VALUE1_VALUE ) values (221,1234)
/


INSERT INTO INT_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (222,null, null)
/

INSERT INTO INT_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (223,2345, null)
/

INSERT INTO INT_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (224,2345, 'NI')
/



INSERT INTO PQ_DATATYPE(ID,VALUE1_VALUE,VALUE1_UNIT) values (300,null, null)
/
INSERT INTO PQ_DATATYPE(ID,VALUE1_VALUE,VALUE1_UNIT) values (301,1234.12, null)
/
INSERT INTO PQ_DATATYPE(ID,VALUE1_VALUE,VALUE1_UNIT) values (302,1234.12, 'GALLON')
/

INSERT INTO PQ_DATATYPE(ID,VALUE2_VALUE) values (303,null)
/
INSERT INTO PQ_DATATYPE(ID,VALUE2_VALUE) values (304,2345.23)
/

INSERT INTO PQ_DATATYPE(ID,VALUE3_VALUE,VALUE3_UNIT,VALUE3_PRECISION,VALUE3_NULL_FLAVOR) values (305,null,null,null,null)
/
INSERT INTO PQ_DATATYPE(ID,VALUE3_VALUE,VALUE3_UNIT,VALUE3_PRECISION,VALUE3_NULL_FLAVOR) values (306,3456.34,null,null,null)
/
INSERT INTO PQ_DATATYPE(ID,VALUE3_VALUE,VALUE3_UNIT,VALUE3_PRECISION,VALUE3_NULL_FLAVOR) values (307,3456.34,'LITER',null,null)
/
INSERT INTO PQ_DATATYPE(ID,VALUE3_VALUE,VALUE3_UNIT,VALUE3_PRECISION,VALUE3_NULL_FLAVOR) values (308,3456.34,'LITER',2,null)
/
INSERT INTO PQ_DATATYPE(ID,VALUE3_VALUE,VALUE3_UNIT,VALUE3_PRECISION,VALUE3_NULL_FLAVOR) values (309,3456.34,'LITER',2,'NI')
/

INSERT INTO PQV_DATATYPE(ID,VALUE1_VALUE) values (310,null)
/
INSERT INTO PQV_DATATYPE(ID,VALUE1_VALUE) values (311,1111.11)
/

INSERT INTO PQV_DATATYPE(ID,VALUE2_VALUE,VALUE2_PRECISION,VALUE2_NULL_FLAVOR) values (312,null,null,null)
/
INSERT INTO PQV_DATATYPE(ID,VALUE2_VALUE,VALUE2_PRECISION,VALUE2_NULL_FLAVOR) values (313,2222.22,null,null)
/
INSERT INTO PQV_DATATYPE(ID,VALUE2_VALUE,VALUE2_PRECISION,VALUE2_NULL_FLAVOR) values (314,2222.22,2,null)
/
INSERT INTO PQV_DATATYPE(ID,VALUE2_VALUE,VALUE2_PRECISION,VALUE2_NULL_FLAVOR) values (315,2222.22,2,'NI')
/


INSERT INTO REAL_DATATYPE(ID,VALUE1_VALUE) values (320,null)
/
INSERT INTO REAL_DATATYPE(ID,VALUE1_VALUE) values (321,1234)
/

INSERT INTO REAL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR) values (322,null,null)
/
INSERT INTO REAL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR) values (323,12345,null)
/
INSERT INTO REAL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR) values (324,12345,'NI')
/


INSERT INTO TS_DATATYPE(ID,VALUE1_VALUE) values (330,null)
/
INSERT INTO TS_DATATYPE(ID,VALUE1_VALUE) values (331,TO_Date( '2010-12-14 12:00:00', 'YYYY-MM-DD HH:MI:SS'))
/

INSERT INTO TS_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR) values (332,null,null)
/
INSERT INTO TS_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR) values (333,TO_Date( '2010-12-13 12:00:00', 'YYYY-MM-DD HH:MI:SS'),null)
/
INSERT INTO TS_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR) values (334,null,'NI')
/


INSERT INTO SC_DATATYPE(ID,VALUE1_VALUE) values ( 340,null)
/
INSERT INTO SC_DATATYPE(ID,VALUE1_VALUE) values ( 341,'VALUE1_VALUE')
/

INSERT INTO SC_DATATYPE(ID,VALUE2_CODE_CODE,VALUE2_CODE_CODE_SYSTEM,VALUE2_CODE_CODE_SYSTEM_NAME,VALUE2_CODE_CODE_SYSTEM_VER,VALUE2_CODE_NULL_FLAVOR
) values (342,null,null,null,null,null)
/
INSERT INTO SC_DATATYPE(ID,VALUE2_CODE_CODE,VALUE2_CODE_CODE_SYSTEM,VALUE2_CODE_CODE_SYSTEM_NAME,VALUE2_CODE_CODE_SYSTEM_VER,VALUE2_CODE_NULL_FLAVOR
) values (343,'VALUE2_CODE_CODE',null,null,null,null)
/
INSERT INTO SC_DATATYPE(ID,VALUE2_CODE_CODE,VALUE2_CODE_CODE_SYSTEM,VALUE2_CODE_CODE_SYSTEM_NAME,VALUE2_CODE_CODE_SYSTEM_VER,VALUE2_CODE_NULL_FLAVOR
) values (344,'VALUE2_CODE_CODE','VALUE2_CODE_CODE_SYSTEM',null,null,null)
/
INSERT INTO SC_DATATYPE(ID,VALUE2_CODE_CODE,VALUE2_CODE_CODE_SYSTEM,VALUE2_CODE_CODE_SYSTEM_NAME,VALUE2_CODE_CODE_SYSTEM_VER,VALUE2_CODE_NULL_FLAVOR
) values (345,'VALUE2_CODE_CODE','VALUE2_CODE_CODE_SYSTEM','VALUE2_CODE_CODE_SYSTEM_NAME',null,null )
/
INSERT INTO SC_DATATYPE(ID,VALUE2_CODE_CODE,VALUE2_CODE_CODE_SYSTEM,VALUE2_CODE_CODE_SYSTEM_NAME,VALUE2_CODE_CODE_SYSTEM_VER,VALUE2_CODE_NULL_FLAVOR
) values (346,'VALUE2_CODE_CODE','VALUE2_CODE_CODE_SYSTEM','VALUE2_CODE_CODE_SYSTEM_NAME','1.1',null )
/
INSERT INTO SC_DATATYPE(ID,VALUE2_CODE_CODE,VALUE2_CODE_CODE_SYSTEM,VALUE2_CODE_CODE_SYSTEM_NAME,VALUE2_CODE_CODE_SYSTEM_VER,VALUE2_CODE_NULL_FLAVOR
) values (347,'VALUE2_CODE_CODE','VALUE2_CODE_CODE_SYSTEM','VALUE2_CODE_CODE_SYSTEM_NAME','1.1','NI' )
/


INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (348,null,null,null,null,null,null,null,null,null,null)
/
INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR
	   ,VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (349,'VALUE3_CODE_CODE',null,null,null,null,null,null,null,null,null)
/
INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (350,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM',null,null,null,null,null,null,null,null)
/
INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (351,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   null,null,null,null,null,null,null)
/

INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (352,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   'VALUE3_CODE_CODE_SYSTEM_VER',null,null,null,null,null,null)
/
INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (353,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   'VALUE3_CODE_CODE_SYSTEM_VER','NI',null,null,null,null,null)
/

INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (354,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   'VALUE3_CODE_CODE_SYSTEM_VER','NI','VALUE3_CODE_DISPLAY_VALUE',null,null,null,null)
/

INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (355,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   'VALUE3_CODE_CODE_SYSTEM_VER','NI','VALUE3_CODE_DISPLAY_VALUE','NI',null,
	   null,null)
/

INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (356,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   'VALUE3_CODE_CODE_SYSTEM_VER','NI','VALUE3_CODE_DISPLAY_VALUE','NI',null,
	   null,null)
/

INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (357,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   'VALUE3_CODE_CODE_SYSTEM_VER','NI','VALUE3_CODE_DISPLAY_VALUE','NI',null,null,null )
/

INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (358,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   'VALUE3_CODE_CODE_SYSTEM_VER','NI','VALUE3_CODE_DISPLAY_VALUE','NI',
	   'VALUE3_CODE_ORIG_TXT_DESC',null,null )
/

INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (359,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   'VALUE3_CODE_CODE_SYSTEM_VER','NI','VALUE3_CODE_DISPLAY_VALUE','NI',
	   'VALUE3_CODE_ORIG_TXT_DESC','VALUE3_CODE_ORIG_TXT_VALUE',null )
/

INSERT INTO SC_DATATYPE(ID,VALUE3_CODE_CODE,VALUE3_CODE_CODE_SYSTEM,VALUE3_CODE_CODE_SYSTEM_NAME,
	   VALUE3_CODE_CODE_SYSTEM_VER,VALUE3_CODE_DISPLAY_NFLAVOR,VALUE3_CODE_DISPLAY_VALUE,VALUE3_CODE_ORIG_TXT_NFLAVOR,
	   VALUE3_CODE_ORIG_TXT_DESC,VALUE3_CODE_ORIG_TXT_VALUE,VALUE3_CODE_NULL_FLAVOR
	   ) values (360,'VALUE3_CODE_CODE','VALUE3_CODE_CODE_SYSTEM','VALUE3_CODE_CODE_SYSTEM_NAME',
	   'VALUE3_CODE_CODE_SYSTEM_VER','NI','VALUE3_CODE_DISPLAY_VALUE','NI',
	   'VALUE3_CODE_ORIG_TXT_DESC','VALUE3_CODE_ORIG_TXT_VALUE','NI' )
/



INSERT INTO ST_DATATYPE(ID,VALUE1_VALUE ) values (400,null)
/

INSERT INTO ST_DATATYPE(ID,VALUE1_VALUE ) values (401,'VALUE1_VALUE')
/


INSERT INTO ST_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (402,null, null)
/

INSERT INTO ST_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (403,'VALUE2_VALUE', null)
/

INSERT INTO ST_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (404,'VALUE2_VALUE', 'NI')
/



INSERT INTO ST_NT_DATATYPE(ID,VALUE1_VALUE ) values (405,null)
/

INSERT INTO ST_NT_DATATYPE(ID,VALUE1_VALUE ) values (406,'VALUE1_VALUE')
/


INSERT INTO ST_NT_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (407,null, null)
/

INSERT INTO ST_NT_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (408,'VALUE2_VALUE', null)
/

INSERT INTO ST_NT_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (409,'VALUE2_VALUE', 'NI')
/



INSERT INTO TEL_DATATYPE(ID,VALUE1_VALUE ) values (430,null)
/

INSERT INTO TEL_DATATYPE(ID,VALUE1_VALUE ) values (431,'tel://301-451-1111')
/


INSERT INTO TEL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (432,null, null)
/

INSERT INTO TEL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (433,'tel://301-451-1112', null)
/

INSERT INTO TEL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (434,'tel://301-451-1113', 'NI')
/


INSERT INTO TEL_EMAIL_DATATYPE(ID,VALUE1_VALUE ) values (435,null)
/

INSERT INTO TEL_EMAIL_DATATYPE(ID,VALUE1_VALUE ) values (436,'mailto:jdoe@nci.gov')
/


INSERT INTO TEL_EMAIL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (437,null, null)
/

INSERT INTO TEL_EMAIL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (438,'MailTo:jdoe@nci.gov', null)
/

INSERT INTO TEL_EMAIL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (439,'MailTo:jdoe@nci.gov', 'NI')
/


INSERT INTO TEL_PERSON_DATATYPE(ID,VALUE1_VALUE ) values (440,null)
/

INSERT INTO TEL_PERSON_DATATYPE(ID,VALUE1_VALUE ) values (441,'tel:8004226237')
/


INSERT INTO TEL_PERSON_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (442,null, null)
/

INSERT INTO TEL_PERSON_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (443,'x-text-tel::8004226237', null)
/

INSERT INTO TEL_PERSON_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (444,'x-text-tel::8004226237', 'NI')
/


INSERT INTO TEL_PHONE_DATATYPE(ID,VALUE1_VALUE ) values (445,null)
/

INSERT INTO TEL_PHONE_DATATYPE(ID,VALUE1_VALUE ) values (446,'tel:8004226237')
/


INSERT INTO TEL_PHONE_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (447,null, null)
/

INSERT INTO TEL_PHONE_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (448,'tel:8004226237', null)
/

INSERT INTO TEL_PHONE_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (449,'tel:8004226237', 'NI')
/


INSERT INTO TEL_URL_DATATYPE(ID,VALUE1_VALUE ) values (450,null)
/

INSERT INTO TEL_URL_DATATYPE(ID,VALUE1_VALUE ) values (451,'https://www.gmail.com')
/


INSERT INTO TEL_URL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (452,null, null)
/

INSERT INTO TEL_URL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (453,'http://www.cancer.gov', null)
/

INSERT INTO TEL_URL_DATATYPE(ID,VALUE2_VALUE,VALUE2_NULL_FLAVOR ) values (454,'http://www.cancer.gov', 'NI')
/



INSERT INTO IVL_INT (ID,
VALUE3_ANY_VALUE,VALUE3_HIGH_VALUE,VALUE3_HIGH_CLOSED,VALUE3_LOW_VALUE,VALUE3_LOW_CLOSED,VALUE3_WIDTH_VALUE,VALUE3_NULL_FLAVOR
) values (1,null,null,null,null,null,null,null)
/
INSERT INTO IVL_INT (ID,
VALUE3_ANY_VALUE,VALUE3_HIGH_VALUE,VALUE3_HIGH_CLOSED,VALUE3_LOW_VALUE,VALUE3_LOW_CLOSED,VALUE3_WIDTH_VALUE,VALUE3_NULL_FLAVOR
) values (2,5,10,'1',2,'1',4,null)
/
INSERT INTO IVL_INT (ID,
VALUE3_ANY_VALUE,VALUE3_HIGH_VALUE,VALUE3_HIGH_CLOSED,VALUE3_LOW_VALUE,VALUE3_LOW_CLOSED,VALUE3_WIDTH_VALUE,VALUE3_NULL_FLAVOR
) values (3,5,10,'1',2,'1',4,'VALUE3_NULL_FLAVOR')
/



INSERT INTO IVL_TS (ID,VALUE1_LOW_VALUE,VALUE1_HIGH_VALUE) values (1,null,null)
/
INSERT INTO IVL_TS (ID,VALUE1_LOW_VALUE,VALUE1_HIGH_VALUE) values (2,TO_Date('2010-12-14 12:00:00','YYYY-MM-DD HH:MI:SS'),null)
/
INSERT INTO IVL_TS (ID,VALUE1_LOW_VALUE,VALUE1_HIGH_VALUE) values (3,TO_Date('2010-12-14 12:00:00','YYYY-MM-DD HH:MI:SS'),TO_Date( '2010-12-15 12:00:00', 'YYYY-MM-DD HH:MI:SS'))
/

INSERT INTO IVL_TS (ID,VALUE2_HIGH_VALUE,VALUE2_LOW_CLOSED) Values (4, null,null)
/

INSERT INTO IVL_TS (ID,VALUE2_HIGH_VALUE,VALUE2_LOW_CLOSED) Values (5,TO_Date('2010-12-14 12:00:00','YYYY-MM-DD HH:MI:SS'),'0' )
/

INSERT INTO IVL_TS (ID,VALUE2_HIGH_VALUE,VALUE2_LOW_CLOSED) Values (6,TO_Date('2010-12-14 12:00:00','YYYY-MM-DD HH:MI:SS'),'1' )
/


INSERT INTO IVL_TS (ID,
VALUE3_HIGH_VALUE,VALUE3_LOW_VALUE,VALUE3_WIDTH_VALUE,VALUE3_NULL_FLAVOR
) values (7,null,null,null,null)
/
INSERT INTO IVL_TS (ID,
VALUE3_HIGH_VALUE,VALUE3_LOW_VALUE,VALUE3_WIDTH_VALUE,VALUE3_NULL_FLAVOR
) values (5,TO_Date( '2010-12-14 12:00:00', 'YYYY-MM-DD HH:MI:SS'),TO_Date( '2010-12-10 12:00:00', 'YYYY-MM-DD HH:MI:SS'),4,null)
/
INSERT INTO IVL_TS (ID,
VALUE3_HIGH_VALUE,VALUE3_LOW_VALUE,VALUE3_WIDTH_VALUE,VALUE3_NULL_FLAVOR
) values (5,TO_Date( '2010-12-14 12:00:00', 'YYYY-MM-DD HH:MI:SS'),TO_Date( '2010-12-10 12:00:00', 'YYYY-MM-DD HH:MI:SS'),4,'NI')
/



INSERT INTO IVL_REAL (ID,VALUE1_LOW_VALUE,VALUE1_HIGH_VALUE) values (1,null,null)
/
INSERT INTO IVL_REAL (ID,VALUE1_LOW_VALUE,VALUE1_HIGH_VALUE) values (2,10,null)
/
INSERT INTO IVL_REAL (ID,VALUE1_LOW_VALUE,VALUE1_HIGH_VALUE) values (3,1,10)
/

INSERT INTO IVL_REAL (ID,VALUE2_HIGH_VALUE,VALUE2_LOW_CLOSED) Values ( 4,null,null)
/

INSERT INTO IVL_REAL (ID,VALUE2_HIGH_VALUE,VALUE2_LOW_CLOSED) Values (5,10,null )
/

INSERT INTO IVL_REAL (ID,VALUE2_HIGH_VALUE,VALUE2_LOW_CLOSED) Values (6,10,'1' )
/


INSERT INTO IVL_REAL (ID,
VALUE3_ANY_VALUE,VALUE3_HIGH_VALUE,VALUE3_HIGH_CLOSED,VALUE3_LOW_VALUE,VALUE3_LOW_CLOSED,VALUE3_WIDTH_VALUE,VALUE3_NULL_FLAVOR
) values (7,null,null,null,null,null,null,null)
/
INSERT INTO IVL_REAL (ID,
VALUE3_ANY_VALUE,VALUE3_HIGH_VALUE,VALUE3_HIGH_CLOSED,VALUE3_LOW_VALUE,VALUE3_LOW_CLOSED,VALUE3_WIDTH_VALUE,VALUE3_NULL_FLAVOR
) values (8,5,10,'1',2,'1',4,null)
/
INSERT INTO IVL_REAL (ID,
VALUE3_ANY_VALUE,VALUE3_HIGH_VALUE,VALUE3_HIGH_CLOSED,VALUE3_LOW_VALUE,VALUE3_LOW_CLOSED,VALUE3_WIDTH_VALUE,VALUE3_NULL_FLAVOR
) values (9,5,10,'1',2,'1',4,'NAV')
/


INSERT INTO IVL_PQ (ID,VALUE1_LOW_VALUE) values (11,null)
/
INSERT INTO IVL_PQ (ID,VALUE1_LOW_VALUE) values (2,1)
/

INSERT INTO IVL_PQ (ID,VALUE2_LOW_VALUE,VALUE2_LOW_PRECISION,VALUE2_LOW_UNIT) Values ( 3,null,null,null)
/

INSERT INTO IVL_PQ (ID,VALUE2_LOW_VALUE,VALUE2_LOW_PRECISION,VALUE2_LOW_UNIT) Values ( 4,1,2,null)
/

INSERT INTO IVL_PQ (ID,VALUE2_LOW_VALUE,VALUE2_LOW_PRECISION,VALUE2_LOW_UNIT) Values ( 5,1,2,'Unit')
/


INSERT INTO IVL_PQ (ID,
    VALUE4_HIGH_VALUE, VALUE4_HIGH_PRECISION, VALUE4_HIGH_UNIT, VALUE4_HIGH_CLOSED, VALUE4_HIGH_NULL_FLAVOR,
	VALUE4_LOW_VALUE,  VALUE4_LOW_PRECISION, VALUE4_LOW_UNIT, VALUE4_LOW_NULL_FLAVOR, VALUE4_LOW_CLOSED,
	VALUE4_WIDTH_VALUE, VALUE4_WIDTH_PRECISION,VALUE4_WIDTH_UNIT, VALUE4_WIDTH_NULL_FLAVOR, VALUE4_NULL_FLAVOR
	) values (6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null)
/
INSERT INTO IVL_PQ (ID,
	   VALUE4_HIGH_VALUE, VALUE4_HIGH_PRECISION, VALUE4_HIGH_UNIT, VALUE4_HIGH_CLOSED, VALUE4_HIGH_NULL_FLAVOR,
	   VALUE4_LOW_VALUE,  VALUE4_LOW_PRECISION, VALUE4_LOW_UNIT, VALUE4_LOW_NULL_FLAVOR, VALUE4_LOW_CLOSED,
	   VALUE4_WIDTH_VALUE, VALUE4_WIDTH_PRECISION,VALUE4_WIDTH_UNIT, VALUE4_WIDTH_NULL_FLAVOR, VALUE4_NULL_FLAVOR
	   ) values (8,5,2,'VALUE4_HIGH_UNIT','1','NAV',1,2,'VALUE4_LOW_UNIT','OTH','1',5,2,'VALUE4_WIDTH_UNIT','QS','NASK')
/


INSERT INTO IVL_PQV (ID,VALUE1_LOW_VALUE) values (1,null)
/
INSERT INTO IVL_PQV (ID,VALUE1_LOW_VALUE) values (2,1)
/

INSERT INTO IVL_PQV (ID,VALUE2_LOW_VALUE,VALUE2_LOW_PRECISION,VALUE2_HIGH_CLOSED) values (3,null,null,null )
/
INSERT INTO IVL_PQV (ID,VALUE2_LOW_VALUE,VALUE2_LOW_PRECISION,VALUE2_HIGH_CLOSED) values (4,1,2,null )
/
INSERT INTO IVL_PQV (ID,VALUE2_LOW_VALUE,VALUE2_LOW_PRECISION,VALUE2_HIGH_CLOSED) values (5,1,2,'1' )
/


INSERT INTO IVL_PQV (ID,VALUE3_LOW_VALUE,VALUE3_LOW_PRECISION,VALUE3_HIGH_VALUE,VALUE3_HIGH_PRECISION,VALUE3_HIGH_NULL_FLAVOR
) values ( 6,null,null,null,null,null)
/
INSERT INTO IVL_PQV (ID,VALUE3_LOW_VALUE,VALUE3_LOW_PRECISION,VALUE3_HIGH_VALUE,VALUE3_HIGH_PRECISION,VALUE3_HIGH_NULL_FLAVOR
) values ( 7,1,2,10,2,null)
/
INSERT INTO IVL_PQV (ID,VALUE3_LOW_VALUE,   VALUE3_LOW_PRECISION,VALUE3_HIGH_VALUE,VALUE3_HIGH_PRECISION,VALUE3_HIGH_NULL_FLAVOR
) values ( 8,1,2,10,2,'NAV')
/

INSERT INTO IVL_PQV (ID,
VALUE4_HIGH_VALUE, VALUE4_HIGH_PRECISION, VALUE4_HIGH_NULL_FLAVOR,
VALUE4_LOW_VALUE,VALUE4_LOW_PRECISION,VALUE4_LOW_NULL_FLAVOR,
VALUE4_WIDTH_VALUE,VALUE4_WIDTH_PRECISION,VALUE4_WIDTH_NULL_FLAVOR
) values (9,null,null,null,null,null,null,null,null,null)
/
INSERT INTO IVL_PQV (ID,
VALUE4_HIGH_VALUE, VALUE4_HIGH_PRECISION, VALUE4_HIGH_NULL_FLAVOR,
VALUE4_LOW_VALUE,VALUE4_LOW_PRECISION,VALUE4_LOW_NULL_FLAVOR,
VALUE4_WIDTH_VALUE,VALUE4_WIDTH_PRECISION,VALUE4_WIDTH_NULL_FLAVOR
) values (10,10,2,'UNC',null,null,null,null,null,null)
/
INSERT INTO IVL_PQV (ID,
VALUE4_HIGH_VALUE, VALUE4_HIGH_PRECISION, VALUE4_HIGH_NULL_FLAVOR,
VALUE4_LOW_VALUE,VALUE4_LOW_PRECISION,VALUE4_LOW_NULL_FLAVOR,
VALUE4_WIDTH_VALUE,VALUE4_WIDTH_PRECISION,VALUE4_WIDTH_NULL_FLAVOR
) values (11,10,2,'TRC',1,2,'NAV',null,null,null)
/
INSERT INTO IVL_PQV (ID,
VALUE4_HIGH_VALUE, VALUE4_HIGH_PRECISION, VALUE4_HIGH_NULL_FLAVOR,
VALUE4_LOW_VALUE,VALUE4_LOW_PRECISION,VALUE4_LOW_NULL_FLAVOR,
VALUE4_WIDTH_VALUE,VALUE4_WIDTH_PRECISION,VALUE4_WIDTH_NULL_FLAVOR
) values (12,10,2,'NAV',1,2,'UNC',5,2,'NI')
/




INSERT INTO DSET_II (ID) values (1000)
/
INSERT INTO DSET_II_VALUE1 (DSET_II_ID, EXTENSION ) values (1000,'Extension')
/


INSERT INTO DSET_II (ID) values (1001)
/
INSERT INTO DSET_II_VALUE2 (DSET_II_ID, EXTENSION, ROOT, NULL_FLAVOR ) values (1001,'Extension','ROOT','INV')
/

INSERT INTO DSET_II (ID) values (1002)
/
INSERT INTO DSET_II_VALUE3 (DSET_II_ID, EXTENSION, IDENTIFIER_NAME ) values (1002,'Extension','IDENTIFIER_NAME')
/


INSERT INTO DSET_II (ID) values (1003)
/
INSERT INTO DSET_II_VALUE4 (DSET_II_ID,ROOT,EXTENSION ,IDENTIFIER_NAME,RELIABILITY,SCOPE,DISPLAYABLE_VALUE,NULL_FLAVOR)
values ( 1003,'Root','Extension','IDENTIFIER_NAME','UNV','OBJ','1','NI')
/

INSERT INTO DSET_II (ID) values (1004)
/
INSERT INTO DSET_II_VALUE5 (ID,DSET_II_ID, EXTENSION ) values (2010,1004,'Extension')
/

INSERT INTO DSET_II (ID) values (1005)
/
INSERT INTO DSET_II_VALUE6 (ID, EXTENSION ) values (2010, 'Extension')
/

INSERT INTO DSET_II_II_VALUE6 (DSET_II_ID, DSET_II_VALUE6_ID ) values (1005,2010)
/




INSERT INTO DSET_TEL (ID,NULL_FLAVOR) values (3000,'NI')
/
INSERT INTO DSET_TEL_VALUE1 (DSET_TEL_ID, TEL_VALUE ) values (3000,'tel://123-456-1234')
/

INSERT INTO DSET_TEL (ID) values (3001)
/
INSERT INTO DSET_TEL_VALUE2 (ID,DSET_TEL_ID, TEL_VALUE ) values (2011,3001,'tel://123-456-5678')
/

INSERT INTO DSET_TEL_VALUE3 (ID, TEL_VALUE) values (1, 'tel://123-456-1212')
/
INSERT INTO DSET_TEL_VALUE3 (ID, TEL_VALUE) values (2,'tel://123-456-3212')
/
INSERT INTO DSET_TEL_TEL_VALUE_3 (DSET_TEL_ID, DSET_TEL_VALUE3_ID ) values (3001,1)
/
INSERT INTO DSET_TEL_TEL_VALUE_3 (DSET_TEL_ID, DSET_TEL_VALUE3_ID ) values (3001,2)
/


INSERT INTO DSET_TEL_EMAIL (ID,NULL_FLAVOR) values (1000,'NI')
/
INSERT INTO DSET_TEL_EMAIL_VALUE1 (DSET_TEL_EMAIL_ID, TEL_EMAIL_VALUE ) values (1000,'TEL_EMAIL_VALUE')
/

INSERT INTO DSET_TEL_EMAIL (ID) values (1001)
/
INSERT INTO DSET_TEL_EMAIL_VALUE1 (DSET_TEL_EMAIL_ID, TEL_EMAIL_VALUE  ) values (1001,'TEL_EMAIL_VALUE')
/


INSERT INTO DSET_TEL_PERSON (ID,NULL_FLAVOR) values (1002,'NI')
/
INSERT INTO DSET_TEL_PERSON_VALUE1 (DSET_TEL_PERSON_ID, TEL_PERSON_VALUE ) values (1002,'TEL_PERSON_VALUE')
/


INSERT INTO DSET_TEL_PHONE (ID,NULL_FLAVOR) values (1003,'NI')
/
INSERT INTO DSET_TEL_PHONE_VALUE1 (DSET_TEL_PHONE_ID, TEL_PHONE_VALUE ) values (1003,'TEL_PHONE_VALUE')
/


INSERT INTO DSET_TEL_URL (ID) values (1004)
/
INSERT INTO DSET_TEL_URL_VALUE1 (DSET_TEL_URL_ID, TEL_URL_VALUE) values (1004,'TEL_URL_VALUE')
/




INSERT INTO DSET_EN (ID) values (1000)
/
INSERT INTO DSET_EN_VALUE1 (DSET_EN_DATATYPE_ID, ENXP_PN_VALUE ) values (1000,'EN_VALUE')
/

INSERT INTO DSET_EN (ID) values (1001)
/
INSERT INTO DSET_EN_VALUE2 (DSET_EN_DATATYPE_ID, ENXP_PN_VALUE, ENXP_PN_CODE ) values (1001,'EN_VALUE','EN_CODE')
/

INSERT INTO DSET_EN (ID) values (1002)
/
INSERT INTO DSET_EN_VALUE3 (DSET_EN_DATATYPE_ID, ENXP_PN_VALUE, ENXP_PN_CODE,ENXP_PN_CODESYSTEM ,ENXP_PN_CODESYSTEMVERSION
) values (1002,'EN_VALUE','EN_CODE','CODESYSTEM','CODESYSTEMVERSION')
/

INSERT INTO DSET_EN (ID) values (1003)
/
INSERT INTO DSET_EN_VALUE4 (DSET_EN_DATATYPE_ID, ENXP_PN_VALUE,ENXP_PN_ENPQ) values (1003,'EN_VALUE','EN_ENPQ')
/

INSERT INTO DSET_EN (ID) values (1004)
/
INSERT INTO DSET_EN_VALUE5 (DSET_EN_DATATYPE_ID ,ENXP_PN_VALUE ,ENXP_PN2_VALUE ,ENXP_PN_CODE ,ENXP_PN2_CODE ,ENXP_PN_CODESYSTEM ,ENXP_PN2_CODESYSTEM ,ENXP_PN2_CODESYSTEMVERSION,	ENXP_PN_CODESYSTEMVERSION
) values (1004,'PN_VALUE','PN2_VALUE','PN_CODE','PN2_CODE','CODESYSTEM','CODESYSTEM2','CODESYSTEMVERSION','CODESYSTEMVERSION2')
/

INSERT INTO DSET_EN (ID) values (1005)
/
INSERT INTO DSET_EN_VALUE6 (
DSET_EN_DATATYPE_ID ,ENXP_PN_VALUE,	ENXP_PN_CODE ,	ENXP_PN_CODESYSTEM ,ENXP_PN_CODESYSTEMVERSION,ENXP_ON_VALUE ,ENXP_ON_CODE ,ENXP_ON_CODESYSTEM ,ENXP_ON_CODESYSTEMVERSION
) values (1005,'PN_VALUE','PN_CODE','CODESYSTEM','CODESYSTEMVERSION','ON_VALUE','ON_CODE','ON_CODESYSTEM','ON_CODESYSTEMVERSION')
/



INSERT INTO DSET_CD (ID) values (1000)
/
INSERT INTO DSET_CD_VALUE1 (DSET_CD_ID, CODE ) values (1000,'CODE')
/

INSERT INTO DSET_CD (ID) values (1001)
/
INSERT INTO DSET_CD_VALUE2 (DSET_CD_ID, CODE, NULL_FLAVOR ) values (1001,'CODE','INV')
/

INSERT INTO DSET_CD (ID) values (1002)
/
INSERT INTO DSET_CD_VALUE3 (DSET_CD_ID, CODE, CODE_SYSTEM, CODE_SYSTEM_NAME ) values (1002,'CODE','CODE_SYSTEM','CODE_SYSTEM_NAME')
/

INSERT INTO DSET_CD (ID) values (1003)
/
INSERT INTO DSET_CD_VALUE4 (DSET_CD_ID,CODE, CODE_SYSTEM, CODE_SYSTEM_VERSION,DISPLAYABLE_VALUE,ORIGINALTEXT_VALUE,ORIGINALTEXT_DESC)
values ( 1003,'CODE','CODE_SYSTEM','CODE_SYSTEM_VERSION','Displ_Val','OrgTextVal','OrgTextDesc')
/

INSERT INTO DSET_CD (ID) values (1004)
/
INSERT INTO DSET_CD_VALUE5 (DSET_CD_ID,CODE, CODE_SYSTEM, CODE_SYSTEM_VERSION,DISPLAYABLE_VALUE,ORIGINALTEXT_VALUE,ORIGINALTEXT_DESC)
values ( 1004,'CODE','CODE_SYSTEM','CODE_SYSTEM_VERSION','Displ_Val','OrgTextVal','OrgTextDesc')
/

INSERT INTO DSET_CD (ID) values (1005)
/
INSERT INTO DSET_CD_VALUE6 (ID,DSET_CD_ID, CODE ) values (2010,1005,'CODE')
/

INSERT INTO DSET_CD (ID) values (1006)
/
INSERT INTO DSET_CD_VALUE7 (ID,CODE ) values (2010, 'CODE')
/
INSERT INTO DSET_CD_CD_VALUE7 (DSET_CD_ID, DSET_CD_VALUE7_ID ) values (1006,2010)
/
INSERT INTO ED_DATATYPE (ID) values (1)
/
INSERT INTO ED_DATATYPE (ID, VALUE1_DATA) values (2, 'C9CBBBCCCEB9C8CABCCCCEB9C9CBBB')
/
INSERT INTO ED_TEXT_DATATYPE (ID) values (1)
/
INSERT INTO ED_TEXT_DATATYPE (ID, VALUE1_VALUE) values (2, 'VALUE1_VALUE')
/
INSERT INTO DSET_AD_DATATYPE (ID) values(1)
/
INSERT INTO DSET_AD_VALUE1 (DSET_AD_DATATYPE_ID,ADXP_AL_VALUE) values(1, 'ADXP_AL_VALUE1')
/
INSERT INTO DSET_AD_VALUE1 (DSET_AD_DATATYPE_ID,ADXP_AL_VALUE) values(1, 'ADXP_AL_VALUE2')
/
